In [1]:
import pandas as pd

In [2]:
# Get in the results dataset

df_comb3 = pd.read_csv("gs://saharadata6/final_data_with_dummies.csv")

In [3]:
df_comb3.head()

,REC_ID,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,...,ETHNICSD_V2:Middle Eastern,ETHNICSD_V2:Unknown,ETHNICSD_V2:Native Amer/Pac Island,ETHNICSD_V2:Other,cluster_0,cluster_2,cluster_5,cluster_3,cluster_4,cluster_1
0,IND_000028457,60137,1,3,1,6,5,2,5,7,...,0,0,0,0,1,0,0,0,0,0
1,IND_000028565,72212,1,4,0,5,2,1,5,6,...,0,0,0,0,1,0,0,0,0,0
2,IND_000028638,60021,4,6,1,1,3,2,4,6,...,0,0,0,0,1,0,0,0,0,0
3,IND_000028963,60085,6,1,0,2,2,6,2,1,...,0,0,0,0,1,0,0,0,0,0
4,IND_000029452,60010,4,5,0,3,1,3,1,5,...,0,0,0,0,1,0,0,0,0,0

In [4]:
df_comb3.shape

(8177217, 180)

In [5]:
#Delete all categorical variables including cluster

cols_to_drop = ['Cluster', 'ETHNICSD_V2', 'SD_GENDER', 'SD_EDUCATION_V2', 'INCOME_GROUP', 'AGE_GROUP', 'SD_HOMEOWNER_PROB_V2']
df_comb3 = df_comb3.drop(columns=cols_to_drop)

In [6]:
# Quick Dimensions Preview
df_comb3.shape

(8177217, 173)

In [7]:
df_comb3.head()

,REC_ID,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,...,ETHNICSD_V2:Middle Eastern,ETHNICSD_V2:Unknown,ETHNICSD_V2:Native Amer/Pac Island,ETHNICSD_V2:Other,cluster_0,cluster_2,cluster_5,cluster_3,cluster_4,cluster_1
0,IND_000028457,60137,1,3,1,6,5,2,5,7,...,0,0,0,0,1,0,0,0,0,0
1,IND_000028565,72212,1,4,0,5,2,1,5,6,...,0,0,0,0,1,0,0,0,0,0
2,IND_000028638,60021,4,6,1,1,3,2,4,6,...,0,0,0,0,1,0,0,0,0,0
3,IND_000028963,60085,6,1,0,2,2,6,2,1,...,0,0,0,0,1,0,0,0,0,0
4,IND_000029452,60010,4,5,0,3,1,3,1,5,...,0,0,0,0,1,0,0,0,0,0

In [10]:
# Create a DataFrame with only Features
features = df_comb3.drop(['REC_ID', 'cluster_0', 'cluster_1', 'cluster_2', 'cluster_3', 'cluster_4', 'cluster_5'], axis = 1)

In [11]:
# Model building

## CLUSTER 0
# Logistic Regression

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features
y = df_comb3['cluster_0']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a logistic regression model
logreg = LogisticRegression(random_state=42)

# Train the model on the training data
logreg.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = logreg.predict(X_test)

# Evaluate the performance of the model
accuracy = logreg.score(X_test, y_test)
print("Accuracy:", accuracy)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

Accuracy: 0.8367556455616946

In [12]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[597104 161116]
 [105861 771363]]

In [13]:
sum(df_comb3['cluster_0'])/len(df_comb3['cluster_0'])

0.5363784524735005

In [14]:
# Proportion of predicted cluster_0
sum(y_pred)/len(y_pred)

0.5701687125942557

In [ ]:
# GAP

In [15]:
## Decision Tree Modeling

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features
y = df_comb3['cluster_0']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a decision tree classifier
dt = DecisionTreeClassifier(random_state=42)

# Train the classifier on the training data
dt.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = dt.predict(X_test)

# Evaluate the performance of the model
accuracy = dt.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9999070588782006

In [16]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[758141     79]
 [    73 877151]]

In [17]:
# Important Features
from pandas._libs.tslibs import dtypes
import numpy as np

# Get the feature importances 
importances = dt.feature_importances_ 

# Get the indices that would sort the importances in ascending order
sorted_indices = np.argsort(importances)
# Print the feature importances in ascending order
for feature, importance in zip(X.columns[sorted_indices], importances[sorted_indices]):
   print(feature, importance)

LT_CAMPING_FAN_V2 0.0
APPAREL_WOMEN_PLUS_V2 0.0
OS_RISKTAKING_FIN 0.0
OS_INNOVATOR 0.0
JOBSSD_HOMEMAKER 0.0
JOB_SEEKER 0.0
SPEC_SPORT_AUTO_MC_V2 0.0
OUTDOOR_GROUPING_V2 0.0
OS_COOKING 0.0
HOME_DECORATING_FAN_V2 0.0
GAMING_SPORTSBOOK_V2 0.0
GAMING_FANTASY_SPORTS_V2 0.0
BEAUTY_COSMETICS 0.0
UBER_LYFT_USER 0.0
LT_DEAL_SITE 0.0
INMARKET_VENMO 0.0
INMARKET_TERM_LIFE 0.0
PREMOVER_NEW_OWNER_V2 0.0
LT_EXERCISE 0.0
HW_JOB_SATIS 0.0
HW_DIET 0.0
EXERCISE_YOGA_V2 0.0
LT_HUNTING_FAN_V2 0.0
MAGAZINE_READER 0.0
VALUE_HUNTER 0.0
age:65+ 0.0
ETHNICSD_V2:Caucasian-Jewish 0.0
ETHNICSD_V2:AA 0.0
ETHNICSD_V2:Asian-Chinese 0.0
ETHNICSD_V2:Asian-Other 0.0
ETHNICSD_V2:Hispanic 0.0
ETHNICSD_V2:Caucasian-Other 0.0
SD_GENDER:Inferred Male 0.0
SD_GENDER:Inferred Female 0.0
SD_GENDER:Female 0.0
SD_GENDER:Male 0.0
EXERCISE_WALKING_V2 0.0
Education:HS Degree 0.0
income:UNKNOWN 0.0
income:Less than $20K 0.0
income:$151K+ 0.0
income:$101K - $150K 0.0
income:$21K - $40K 0.0
income:$61K - $80K 0.0
age:55-64 0.0
age:35-44 0.0
age:UNKNOWN 0.0
age:45-54 0.0
Education:Bachelor Degree 0.0
EXERCISE_RUNNING_JOGGING_V2 0.0
ETHNICSD_V2:Other 0.0
CC_NEW_ISSUE 0.0
TV_FAVORITES_LIVE_SPORTS 0.0
CC_USER 0.0
SOCIALSD_TWITTER 0.0
SOCIALSD_TRIP_ADVISOR 0.0
YOUNG_ADULT_IN_HH 0.0
LT_SENIOR_ADULT_IN_HH_V2 0.0
TV_FAVORITES_NEWS 0.0
SMARTPHONE_ANDROID_SCALE 0.0
EXERCISE_PILATES_BARRE_V2 0.0
AUTOMOTIVE_BUFF_V2 0.0
AUTO_AVG_MILEAGE 0.0
EXERCISE_AEROBIC_V2 0.0
CHILDREN_AGED_6_10 0.0
TV_STREAMING_SERV_MANY 0.0
JOBSSD_SALES 1.561531836028049e-08
JOBSSD_CORP_LEADER 5.970954043221746e-08
Education:Less Than HS 7.422282247005165e-08
ETHNICSD_V2:Asian-Indian 1.5144190465375232e-07
JOBSSD_STUDENT 1.5145092310478211e-07
ETHNICSD_V2:Unknown 1.5602848714563886e-07
OS_LAGGARD 1.7563109659370506e-07
SD_EMPLOYMENT 2.9159265396006083e-07
SOCIALSD_LINKEDIN_V2 2.9198669808703385e-07
JEWELRY_PURCHASER 3.0531862787179715e-07
ONLINE_PURCHASER 3.073544190389836e-07
LT_HOME_FURNISHINGS_DECO_V2 3.073544190389836e-07
LT_TRAVEL_DOMESTIC_V2 3.43351470719878e-07
age:25-34 4.09805892051978e-07
HW_JUNK_DIET 4.09805892051978e-07
JOBSSD_RETIRED 4.09805892051978e-07
CHILDREN_AGED_0_2 4.09805892051978e-07
LT_TV_DAILY_VIEWING_V2 4.610316285584753e-07
SMARTPHONE_NONE_SCALE 4.610316285584753e-07
LT_HUNTING_SHOOTING_FAN_V2 4.610316285584753e-07
LT_FISHING_FAN_V2 4.796436461558371e-07
CHILDREN_AGED_16_17 4.838077322740721e-07
SOCIALSD_INSTAGRAM_V2 4.917670704623736e-07
LT_SPEC_SPORT_AUTO_MC_V2 4.917670704623736e-07
TV_CABLE_V2 4.917670704623736e-07
LT_GAMING_FANTASY_SPORTS_V2 5.122573650649726e-07
PARENTING_CATEGORY 5.261780205983929e-07
ETHNICSD_V2:Native Amer/Pac Island 5.407940767261264e-07
HW_STRESS_V2 5.461551568758268e-07
LT_HOME_IMPROVEMENT_V2 5.558818632511508e-07
JOB_SEEKER_ACTIVE 5.575266205823421e-07
SD_BUSINESS_OWNER_V2 5.674235428412001e-07
TEAM_SPORTS_V2 5.70801063929541e-07
LT_GOLF_FAN_V2 5.737282488727694e-07
INMARKET_ONLINEEDU_V2 5.85436988645683e-07
HS_TRAVEL_BUSINESS 5.879823668571861e-07
OS_FIN_IMPCONTROL 6.042900442122391e-07
age:18-24 6.623034962774374e-07
HEALTH_BEAUTY 6.659345745844644e-07
SD_GENDER:Unknown 6.6729075192994e-07
TV_VIEWER_EMPATHIZER 6.896662717230679e-07
LT_GAMING_SPORTSBOOK_V2 7.376506056935604e-07
EXERCISE_FAN_V2 7.384960651957788e-07
OS_FOODIE 7.764743217826959e-07
INMARKET_PAYPAL 8.879127661126192e-07
LT_TEAM_SPORTS_V2 8.984206094985676e-07
LT_PET_OWNER_V2 9.064055791659075e-07
SOCIALSD_DEAL_SITE 9.476761253701992e-07
SOCIALSD_PINTEREST 9.86095427750072e-07
CHILDREN_AGED_11_15 1.0142695828286453e-06
LT_COUPONER 1.0235313189154242e-06
ZIPCAR_USER 1.0537865795622292e-06
JOBSSD_MIDDLE_MGMT 1.0581912298914934e-06
TV_FAVORITES_HOME_IMP 1.0703165651239897e-06
CHILDREN_AGED_3_5 1.0757404666364423e-06
OS_VALUE_SEEKER 1.1359550744538056e-06
LT_EXERCISE_WALKING_V2 1.1679467923481375e-06
INMARKET_ONLINEDATE 1.229417676155934e-06
Education:Graduate Degree 1.2381992309856192e-06
LT_HOME_GARDEN_V2 1.290888559963731e-06
HW_SLEEP_V3 1.3025972997366445e-06
HW_SMOKING 1.326877187874493e-06
SOCIALSD_TUMBLR 1.3611409986012128e-06
CHANNELSD_INTERTV_SCALE 1.379154444405695e-06
LT_EXERCISE_PILATES_BARRE_V2 1.4669188181406036e-06
REGB_FINTECH_MWALLET 1.4753012113871209e-06
SOCIALSD_SNAPCHAT 1.5162818005923185e-06
ETHNICSD_V2:Middle Eastern 1.5356565409831368e-06
LT_DOG_OWNER_V2 1.5473638828184425e-06
OS_MATERIALISM 1.751111361103682e-06
HW_YOGAPILATE 1.9017952393382647e-06
YOUTUBE_CREATOR 1.9162651758860093e-06
SOCIALSD_FACEBOOK_V2 2.0768377172205603e-06
LT_CAT_OWNER_V2 2.195105431459063e-06
SD_LOR_V2 2.2071407254662347e-06
JOBSSD_BLUE_COLLAR 2.4649092542266506e-06
OS_FIN_PLANNING 2.514430936563989e-06
REGB_FINTECH_DIGITAL 2.6028455420509136e-06
PRESENCE_OF_CC 2.722779278364451e-06
PREMOVER_V2 2.896802411658865e-06
LT_EXERCISE_FAN_V2 3.100944002939822e-06
HOME_PURCHASE_PRICE 3.160870324725394e-06
CHANNELSD_BANNER_SCALE 3.2329281266955777e-06
SMARTPHONE_IPHONE_SCALE 3.3085799225961174e-06
AUTO_AGE 3.4771227494835592e-06
REGB_CC_AIRLINE_IM 3.834366272070164e-06
income:$41K - $60K 4.061096036138621e-06
TRAVELPROP_INTL 4.264078830654391e-06
income:$81K - $100K 9.237485561316018e-06
TRAVELPROP_DOMESTIC 3.272344882951647e-05
SPENDEX_PERSONAL_V2 5.890155816540339e-05
SPENDEX_TRAVEL_CRUISE_V2 0.0001902554592747445
SPENDEX_TRAVEL_DOM_V2 0.00022248394920939738
SPENDEX_APPAREL_V2 0.00037523602913096265
CHANGE_IN_INCOME_12MO 0.0004548475396234305
SPENDEX_TRAVEL_INTL_V2 0.0009390961771678325
SPENDEX_TRAVEL_V2 0.002121842534012264
SPENDEX_EDUCATION_V2 0.004387473148159123
ZIP5 0.3644704493112718
SPENDEX_PLUS_V2 0.6266341089036156

In [ ]:
# GAP

In [18]:
## CLUSTER 2

# Preparing file for cluster_2 prediction

# First make predictions using the decision tree
predictions0 = dt.predict(features) 
df_comb3['predictions0'] = predictions0 
df_comb3

,REC_ID,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,...,ETHNICSD_V2:Unknown,ETHNICSD_V2:Native Amer/Pac Island,ETHNICSD_V2:Other,cluster_0,cluster_2,cluster_5,cluster_3,cluster_4,cluster_1,predictions0
0,IND_000028457,60137,1,3,1,6,5,2,5,7,...,0,0,0,1,0,0,0,0,0,1
1,IND_000028565,72212,1,4,0,5,2,1,5,6,...,0,0,0,1,0,0,0,0,0,1
2,IND_000028638,60021,4,6,1,1,3,2,4,6,...,0,0,0,1,0,0,0,0,0,1
3,IND_000028963,60085,6,1,0,2,2,6,2,1,...,0,0,0,1,0,0,0,0,0,1
4,IND_000029452,60010,4,5,0,3,1,3,1,5,...,0,0,0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8177212,IND_007676373,60448,6,2,0,1,1,4,1,7,...,0,0,0,0,0,1,0,0,0,0
8177213,IND_007676499,94920,7,6,1,3,3,2,1,7,...,0,0,0,0,1,0,0,0,0,0
8177214,IND_006036196,60101,3,4,0,5,7,3,5,6,...,1,0,0,1,0,0,0,0,0,1
8177215,IND_006037234,60466,4,5,0,6,6,2,6,6,...,0,0,0,1,0,0,0,0,0,1
8177216,IND_006038306,60051,4,4,0,3,1,7,4,2,...,0,0,0,1,0,0,0,0,0,1

In [19]:
# Drop columns 
df_comb3_no0 = df_comb3[df_comb3["predictions0"] < 0.5].drop("predictions0", axis=1)

In [20]:
df_comb3_no0

,REC_ID,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,...,ETHNICSD_V2:Middle Eastern,ETHNICSD_V2:Unknown,ETHNICSD_V2:Native Amer/Pac Island,ETHNICSD_V2:Other,cluster_0,cluster_2,cluster_5,cluster_3,cluster_4,cluster_1
9,IND_000031316,95409,6,2,0,4,1,6,4,5,...,0,0,0,0,0,1,0,0,0,0
10,IND_000031503,94928,7,2,0,4,3,6,2,6,...,0,0,0,0,0,1,0,0,0,0
11,IND_000032374,60025,7,3,0,3,1,3,1,7,...,0,0,0,0,0,0,1,0,0,0
15,IND_000035522,94123,7,2,0,3,3,3,2,7,...,0,0,0,0,0,0,0,1,0,0
20,IND_000036461,94546,7,1,0,4,1,4,2,6,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8177209,IND_007675463,95123,7,2,0,4,5,4,4,7,...,0,0,0,0,0,1,0,0,0,0
8177210,IND_007676031,95118,6,4,0,7,7,2,4,7,...,0,0,0,0,0,0,0,0,1,0
8177211,IND_007676034,95122,6,3,0,5,5,4,4,5,...,0,0,0,0,0,1,0,0,0,0
8177212,IND_007676373,60448,6,2,0,1,1,4,1,7,...,0,0,0,0,0,0,1,0,0,0
8177213,IND_007676499,94920,7,6,1,3,3,2,1,7,...,0,0,0,0,0,1,0,0,0,0

In [25]:
# Model building for cluster_2

# Create a dataframe with just the features without cluster 0 
features_no0 = df_comb3_no0.drop(['REC_ID', 'cluster_0', 'cluster_1', 'cluster_2', 'cluster_3', 'cluster_4', 'cluster_5'], axis = 1)
features_no0

,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,SMARTPHONE_NONE_SCALE,...,ETHNICSD_V2:Hispanic,ETHNICSD_V2:Asian-Other,ETHNICSD_V2:Asian-Chinese,ETHNICSD_V2:Asian-Indian,ETHNICSD_V2:AA,ETHNICSD_V2:Caucasian-Jewish,ETHNICSD_V2:Middle Eastern,ETHNICSD_V2:Unknown,ETHNICSD_V2:Native Amer/Pac Island,ETHNICSD_V2:Other
9,95409,6,2,0,4,1,6,4,5,6,...,0,0,0,0,0,0,0,0,0,0
10,94928,7,2,0,4,3,6,2,6,3,...,0,1,0,0,0,0,0,0,0,0
11,60025,7,3,0,3,1,3,1,7,4,...,0,0,0,0,0,0,0,0,0,0
15,94123,7,2,0,3,3,3,2,7,3,...,0,0,0,0,0,0,0,0,0,0
20,94546,7,1,0,4,1,4,2,6,6,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8177209,95123,7,2,0,4,5,4,4,7,2,...,1,0,0,0,0,0,0,0,0,0
8177210,95118,6,4,0,7,7,2,4,7,3,...,0,0,0,0,0,0,0,0,0,0
8177211,95122,6,3,0,5,5,4,4,5,2,...,0,1,0,0,0,0,0,0,0,0
8177212,60448,6,2,0,1,1,4,1,7,2,...,0,0,0,0,0,0,0,0,0,0
8177213,94920,7,6,1,3,3,2,1,7,3,...,0,0,0,0,0,0,0,0,0,0

In [26]:
## Logisitc Regression

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no0
y = df_comb3_no0['cluster_2']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a logistic regression model
logreg = LogisticRegression(random_state=42)

# Train the model on the training data
logreg.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = logreg.predict(X_test)

# Evaluate the performance of the model
accuracy = logreg.score(X_test, y_test)
print("Accuracy:", accuracy)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

Accuracy: 0.9821913255414613

In [27]:
# Confusion matrix for cluster 2

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[427775   6505]
 [  6998 316948]]

In [28]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no0
y = df_comb3_no0['cluster_2']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a decision tree classifier
dt = DecisionTreeClassifier(random_state=42)

# Train the classifier on the training data
dt.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = dt.predict(X_test)

# Evaluate the performance of the model
accuracy = dt.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9999300999965709

In [29]:
# Confusion matrix Decision Tree
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[434251     29]
 [    24 323922]]

In [30]:
# Important Features
from pandas._libs.tslibs import dtypes
import numpy as np
# Get the feature importances 
importances = dt.feature_importances_ 

# Get the indices that would sort the importances in ascending order
sorted_indices = np.argsort(importances)
# Print the feature importances in ascending order
for feature, importance in zip(X.columns[sorted_indices], importances[sorted_indices]):
   print(feature, importance)

ETHNICSD_V2:Other 0.0
SPEC_SPORT_AUTO_MC_V2 0.0
PARENTING_CATEGORY 0.0
OUTDOOR_GROUPING_V2 0.0
OS_FOODIE 0.0
income:UNKNOWN 0.0
LT_TEAM_SPORTS_V2 0.0
LT_SPEC_SPORT_AUTO_MC_V2 0.0
Education:Graduate Degree 0.0
LT_HOME_FURNISHINGS_DECO_V2 0.0
LT_GAMING_SPORTSBOOK_V2 0.0
LT_GAMING_FANTASY_SPORTS_V2 0.0
LT_FISHING_FAN_V2 0.0
TEAM_SPORTS_V2 0.0
ETHNICSD_V2:Native Amer/Pac Island 0.0
GAMING_FANTASY_SPORTS_V2 0.0
BEAUTY_COSMETICS 0.0
ZIPCAR_USER 0.0
UBER_LYFT_USER 0.0
Education:HS Degree 0.0
Education:Less Than HS 0.0
LT_DEAL_SITE 0.0
INMARKET_VENMO 0.0
INMARKET_TERM_LIFE 0.0
SD_GENDER:Male 0.0
age:65+ 0.0
PREMOVER_NEW_OWNER_V2 0.0
HOME_DECORATING_FAN_V2 0.0
JOB_SEEKER 0.0
JOB_SEEKER_ACTIVE 0.0
JOBSSD_BLUE_COLLAR 0.0
age:25-34 0.0
age:18-24 0.0
age:55-64 0.0
income:$61K - $80K 0.0
income:$81K - $100K 0.0
income:$21K - $40K 0.0
income:$101K - $150K 0.0
LT_TRAVEL_DOMESTIC_V2 0.0
HS_TRAVEL_BUSINESS 0.0
VALUE_HUNTER 0.0
ONLINE_PURCHASER 0.0
MAGAZINE_READER 0.0
LT_HUNTING_FAN_V2 0.0
income:$41K - $60K 0.0
LT_COUPONER 0.0
JEWELRY_PURCHASER 0.0
HEALTH_BEAUTY 0.0
APPAREL_WOMEN_PLUS_V2 0.0
OS_VALUE_SEEKER 0.0
OS_RISKTAKING_FIN 0.0
income:$151K+ 0.0
OS_LAGGARD 0.0
OS_INNOVATOR 0.0
SD_EMPLOYMENT 0.0
SD_BUSINESS_OWNER_V2 0.0
income:Less than $20K 0.0
JOBSSD_CORP_LEADER 0.0
SD_GENDER:Female 0.0
SD_GENDER:Inferred Female 0.0
INMARKET_ONLINEDATE 0.0
ETHNICSD_V2:Caucasian-Jewish 0.0
YOUNG_ADULT_IN_HH 0.0
ETHNICSD_V2:AA 0.0
LT_SENIOR_ADULT_IN_HH_V2 0.0
LT_DOG_OWNER_V2 0.0
LT_EXERCISE 0.0
CHILDREN_AGED_3_5 0.0
CHILDREN_AGED_16_17 0.0
CHILDREN_AGED_11_15 0.0
CHILDREN_AGED_0_2 0.0
YOUTUBE_CREATOR 0.0
ETHNICSD_V2:Middle Eastern 0.0
TV_FAVORITES_LIVE_SPORTS 0.0
TV_CABLE_V2 0.0
SOCIALSD_TWITTER 0.0
SOCIALSD_TRIP_ADVISOR 0.0
SOCIALSD_PINTEREST 0.0
SOCIALSD_LINKEDIN_V2 0.0
SOCIALSD_DEAL_SITE 0.0
SMARTPHONE_NONE_SCALE 0.0
SMARTPHONE_ANDROID_SCALE 0.0
LT_TV_DAILY_VIEWING_V2 0.0
CHANNELSD_BANNER_SCALE 0.0
AUTOMOTIVE_BUFF_V2 0.0
AUTO_AVG_MILEAGE 0.0
AUTO_AGE 0.0
CC_NEW_ISSUE 0.0
CC_USER 0.0
age:45-54 0.0
EXERCISE_FAN_V2 0.0
ETHNICSD_V2:Asian-Indian 0.0
HW_STRESS_V2 0.0
OS_FIN_PLANNING 0.0
PRESENCE_OF_CC 0.0
SD_GENDER:Unknown 0.0
ETHNICSD_V2:Asian-Chinese 0.0
ETHNICSD_V2:Asian-Other 0.0
EXERCISE_PILATES_BARRE_V2 0.0
ETHNICSD_V2:Hispanic 0.0
HW_DIET 0.0
ETHNICSD_V2:Caucasian-Other 0.0
EXERCISE_AEROBIC_V2 0.0
EXERCISE_YOGA_V2 0.0
EXERCISE_WALKING_V2 0.0
EXERCISE_RUNNING_JOGGING_V2 0.0
CHILDREN_AGED_6_10 1.4527926840675563e-07
SD_GENDER:Inferred Male 2.0426329545334984e-07
TV_FAVORITES_HOME_IMP 4.360110527329785e-07
CHANGE_IN_INCOME_12MO 4.4036217561895917e-07
TV_FAVORITES_NEWS 5.9884606909362e-07
LT_GOLF_FAN_V2 6.401224238228466e-07
ETHNICSD_V2:Unknown 6.477902189714656e-07
JOBSSD_MIDDLE_MGMT 6.716160635577764e-07
LT_EXERCISE_PILATES_BARRE_V2 6.737018277303223e-07
SOCIALSD_TUMBLR 6.737018277303223e-07
GAMING_SPORTSBOOK_V2 6.737018277303223e-07
INMARKET_PAYPAL 6.737018277303223e-07
SOCIALSD_INSTAGRAM_V2 6.737018277303223e-07
CHANNELSD_INTERTV_SCALE 8.982691036404296e-07
HW_SLEEP_V3 8.982691036404296e-07
SOCIALSD_FACEBOOK_V2 8.982691036404296e-07
Education:Bachelor Degree 8.982691036404296e-07
HW_SMOKING 1.0105527415954835e-06
JOBSSD_STUDENT 1.0779229243685155e-06
TV_STREAMING_SERV_MANY 1.0868521071932594e-06
PREMOVER_V2 1.1228363795505373e-06
HW_JOB_SATIS 1.152338355013238e-06
SOCIALSD_SNAPCHAT 1.1549174189662668e-06
age:35-44 1.1549174189662668e-06
JOBSSD_RETIRED 1.1976921381872394e-06
LT_HUNTING_SHOOTING_FAN_V2 1.2561411552049384e-06
HW_YOGAPILATE 1.2575767450966012e-06
JOBSSD_SALES 1.2582572519932994e-06
LT_PET_OWNER_V2 1.2681446169041361e-06
LT_CAMPING_FAN_V2 1.2716244222979418e-06
LT_HOME_GARDEN_V2 1.3009414604447594e-06
OS_COOKING 1.3284261391865509e-06
HOME_PURCHASE_PRICE 1.3411592579302083e-06
LT_EXERCISE_FAN_V2 1.342495625018967e-06
SD_LOR_V2 1.5795704293020596e-06
age:UNKNOWN 1.6226796710923882e-06
LT_CAT_OWNER_V2 1.6842545693258057e-06
HW_JUNK_DIET 1.7061111532397723e-06
JOBSSD_HOMEMAKER 1.7445505407593548e-06
SMARTPHONE_IPHONE_SCALE 1.841967542663339e-06
REGB_FINTECH_MWALLET 2.5009591435083176e-06
LT_HOME_IMPROVEMENT_V2 2.5151534901932033e-06
TV_VIEWER_EMPATHIZER 2.52156969807635e-06
OS_MATERIALISM 2.552975347188591e-06
REGB_CC_AIRLINE_IM 2.8736269551097703e-06
REGB_FINTECH_DIGITAL 3.1381465782018897e-06
LT_EXERCISE_WALKING_V2 3.4743765687235193e-06
SPENDEX_TRAVEL_INTL_V2 4.434479240866529e-06
OS_FIN_IMPCONTROL 6.005570578624587e-06
INMARKET_ONLINEEDU_V2 6.5616408277581936e-06
TRAVELPROP_INTL 4.1554772322648776e-05
SPENDEX_TRAVEL_DOM_V2 4.7327032296168895e-05
SPENDEX_APPAREL_V2 7.973866426434922e-05
TRAVELPROP_DOMESTIC 0.00018508217160357623
SPENDEX_TRAVEL_CRUISE_V2 0.00018764979680198175
SPENDEX_EDUCATION_V2 0.0005928430089595084
SPENDEX_TRAVEL_V2 0.0038850167517367295
SPENDEX_PLUS_V2 0.02893088904483897
SPENDEX_PERSONAL_V2 0.45705318235919695
ZIP5 0.5089186300933657

In [35]:
import xgboost as xgb

In [34]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-1.6.2-py3-none-manylinux2014_x86_64.whl (255.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 255.9/255.9 MB 4.0 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: scipy in /opt/conda/lib/python3.7/site-packages (from xgboost) (1.7.3)
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from xgboost) (1.21.6)
Installing collected packages: xgboost
Successfully installed xgboost-1.6.2
Note: you may need to restart the kernel to use updated packages.

In [36]:
# Gradient Boost

import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split

# Load the data into a pandas dataframe

# Split the data into training and testing sets
X = features_no0
y = df_comb3_no0['cluster_2']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Set up the XGBoost model
params = {'objective': 'binary:logistic', 'eval_metric': 'auc'}
num_rounds = 10
early_stopping_rounds = 50
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# Train the model
model = xgb.train(params, dtrain, num_rounds, evals=[(dtest, 'test')], early_stopping_rounds=early_stopping_rounds)

# Make predictions on the test set
y_pred = model.predict(dtest)

# Calculate the accuracy score
threshold = 0.5
y_pred_binary = [1 if p > threshold else 0 for p in y_pred]
accuracy = sum(y_pred_binary == y_test) / len(y_test)
print('Accuracy: %.2f%%' % (accuracy * 100.0))

[0]	test-auc:1.00000
[1]	test-auc:1.00000
[2]	test-auc:1.00000
[3]	test-auc:1.00000
[4]	test-auc:1.00000
[5]	test-auc:1.00000
[6]	test-auc:1.00000
[7]	test-auc:1.00000
[8]	test-auc:1.00000
[9]	test-auc:1.00000
Accuracy: 99.99%

In [ ]:
# GAP

In [40]:
## CLUSTER 5

# Preparing file for cluster_5 prediction

# First make predictions using the decision tree for Cluster 2
predictions2 = dt.predict(features_no0) 
df_comb3_no0['predictions2'] = predictions2
df_comb3_no0

,REC_ID,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,...,ETHNICSD_V2:Unknown,ETHNICSD_V2:Native Amer/Pac Island,ETHNICSD_V2:Other,cluster_0,cluster_2,cluster_5,cluster_3,cluster_4,cluster_1,predictions2
9,IND_000031316,95409,6,2,0,4,1,6,4,5,...,0,0,0,0,1,0,0,0,0,1
10,IND_000031503,94928,7,2,0,4,3,6,2,6,...,0,0,0,0,1,0,0,0,0,1
11,IND_000032374,60025,7,3,0,3,1,3,1,7,...,0,0,0,0,0,1,0,0,0,0
15,IND_000035522,94123,7,2,0,3,3,3,2,7,...,0,0,0,0,0,0,1,0,0,0
20,IND_000036461,94546,7,1,0,4,1,4,2,6,...,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8177209,IND_007675463,95123,7,2,0,4,5,4,4,7,...,0,0,0,0,1,0,0,0,0,1
8177210,IND_007676031,95118,6,4,0,7,7,2,4,7,...,0,0,0,0,0,0,0,1,0,0
8177211,IND_007676034,95122,6,3,0,5,5,4,4,5,...,0,0,0,0,1,0,0,0,0,1
8177212,IND_007676373,60448,6,2,0,1,1,4,1,7,...,0,0,0,0,0,1,0,0,0,0
8177213,IND_007676499,94920,7,6,1,3,3,2,1,7,...,0,0,0,0,1,0,0,0,0,1

In [41]:
# Drop columns 
df_comb3_no02 = df_comb3_no0[df_comb3_no0["predictions2"] < 0.5].drop("predictions2", axis=1)

In [42]:
# Quick check
df_comb3_no02

,REC_ID,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,...,ETHNICSD_V2:Middle Eastern,ETHNICSD_V2:Unknown,ETHNICSD_V2:Native Amer/Pac Island,ETHNICSD_V2:Other,cluster_0,cluster_2,cluster_5,cluster_3,cluster_4,cluster_1
11,IND_000032374,60025,7,3,0,3,1,3,1,7,...,0,0,0,0,0,0,1,0,0,0
15,IND_000035522,94123,7,2,0,3,3,3,2,7,...,0,0,0,0,0,0,0,1,0,0
22,IND_000036727,60010,7,4,0,5,2,2,1,5,...,0,0,0,0,0,0,0,1,0,0
27,IND_004561271,60712,4,5,0,2,4,2,4,7,...,0,0,0,0,0,0,1,0,0,0
28,IND_004562054,95014,7,3,0,3,5,2,1,7,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8177198,IND_003772879,60565,6,7,1,2,4,1,4,7,...,0,0,0,0,0,0,1,0,0,0
8177205,IND_001414864,95123,7,3,0,6,2,2,2,7,...,0,0,0,0,0,0,0,0,1,0
8177207,IND_007674098,60007,6,1,0,3,4,5,2,6,...,0,0,0,0,0,0,1,0,0,0
8177210,IND_007676031,95118,6,4,0,7,7,2,4,7,...,0,0,0,0,0,0,0,0,1,0
8177212,IND_007676373,60448,6,2,0,1,1,4,1,7,...,0,0,0,0,0,0,1,0,0,0

In [43]:
# Model building for cluster_5

# Create a dataframe with just the features without cluster 0 
features_no02 = df_comb3_no02.drop(['REC_ID', 'cluster_0', 'cluster_1', 'cluster_2', 'cluster_3', 'cluster_4', 'cluster_5'], axis = 1)
features_no02

,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,SMARTPHONE_NONE_SCALE,...,ETHNICSD_V2:Hispanic,ETHNICSD_V2:Asian-Other,ETHNICSD_V2:Asian-Chinese,ETHNICSD_V2:Asian-Indian,ETHNICSD_V2:AA,ETHNICSD_V2:Caucasian-Jewish,ETHNICSD_V2:Middle Eastern,ETHNICSD_V2:Unknown,ETHNICSD_V2:Native Amer/Pac Island,ETHNICSD_V2:Other
11,60025,7,3,0,3,1,3,1,7,4,...,0,0,0,0,0,0,0,0,0,0
15,94123,7,2,0,3,3,3,2,7,3,...,0,0,0,0,0,0,0,0,0,0
22,60010,7,4,0,5,2,2,1,5,3,...,0,0,0,0,0,0,0,0,0,0
27,60712,4,5,0,2,4,2,4,7,3,...,0,0,1,0,0,0,0,0,0,0
28,95014,7,3,0,3,5,2,1,7,4,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8177198,60565,6,7,1,2,4,1,4,7,1,...,0,0,0,0,0,0,0,0,0,0
8177205,95123,7,3,0,6,2,2,2,7,4,...,0,0,0,0,0,0,0,0,0,0
8177207,60007,6,1,0,3,4,5,2,6,4,...,0,0,0,0,0,0,0,0,0,0
8177210,95118,6,4,0,7,7,2,4,7,3,...,0,0,0,0,0,0,0,0,0,0
8177212,60448,6,2,0,1,1,4,1,7,2,...,0,0,0,0,0,0,0,0,0,0

In [44]:
# Let's start with Logistic again
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no02
y = df_comb3_no02['cluster_5']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a logistic regression model
logreg = LogisticRegression(random_state=42)

# Train the model on the training data
logreg.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = logreg.predict(X_test)

# Evaluate the performance of the model
accuracy = logreg.score(X_test, y_test)
print("Accuracy:", accuracy)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

Accuracy: 0.8758732804951621

In [45]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[175772  12798]
 [ 41108 204604]]

In [46]:
# Random Forest (Cluster 5)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no02
y = df_comb3_no02['cluster_5']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a random forest classifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the training data
rf.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = rf.predict(X_test)

# Evaluate the performance of the model
accuracy = rf.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9997835507803685

In [47]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[188519     51]
 [    43 245669]]

In [48]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no02
y = df_comb3_no02['cluster_5']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a decision tree classifier
dt = DecisionTreeClassifier(random_state=42)

# Train the classifier on the training data
dt.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = dt.predict(X_test)

# Evaluate the performance of the model
accuracy = dt.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9998940780414569

In [49]:
#confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[188556     14]
 [    32 245680]]

In [50]:
from pandas._libs.tslibs import dtypes
import numpy as np
# Get the feature importances 
importances = dt.feature_importances_ 

# Get the indices that would sort the importances in ascending order
sorted_indices = np.argsort(importances)
# Print the feature importances in ascending order
for feature, importance in zip(X.columns[sorted_indices], importances[sorted_indices]):
   print(feature, importance)

LT_CAMPING_FAN_V2 0.0
OS_INNOVATOR 0.0
JOBSSD_STUDENT 0.0
JOBSSD_RETIRED 0.0
JOBSSD_MIDDLE_MGMT 0.0
JOBSSD_CORP_LEADER 0.0
JOB_SEEKER 0.0
TEAM_SPORTS_V2 0.0
PARENTING_CATEGORY 0.0
OUTDOOR_GROUPING_V2 0.0
LT_SPEC_SPORT_AUTO_MC_V2 0.0
LT_HUNTING_SHOOTING_FAN_V2 0.0
OS_MATERIALISM 0.0
LT_HOME_IMPROVEMENT_V2 0.0
LT_GAMING_FANTASY_SPORTS_V2 0.0
ETHNICSD_V2:Native Amer/Pac Island 0.0
GAMING_SPORTSBOOK_V2 0.0
GAMING_FANTASY_SPORTS_V2 0.0
BEAUTY_COSMETICS 0.0
UBER_LYFT_USER 0.0
LT_DEAL_SITE 0.0
INMARKET_PAYPAL 0.0
INMARKET_ONLINEEDU_V2 0.0
INMARKET_ONLINEDATE 0.0
PREMOVER_NEW_OWNER_V2 0.0
LT_GAMING_SPORTSBOOK_V2 0.0
OS_RISKTAKING_FIN 0.0
APPAREL_WOMEN_PLUS_V2 0.0
HEALTH_BEAUTY 0.0
ETHNICSD_V2:Unknown 0.0
ETHNICSD_V2:Caucasian-Jewish 0.0
ETHNICSD_V2:AA 0.0
ETHNICSD_V2:Asian-Indian 0.0
ETHNICSD_V2:Asian-Chinese 0.0
ETHNICSD_V2:Asian-Other 0.0
ETHNICSD_V2:Caucasian-Other 0.0
SD_GENDER:Unknown 0.0
SD_GENDER:Inferred Male 0.0
SD_GENDER:Female 0.0
SD_GENDER:Male 0.0
Education:HS Degree 0.0
Education:Bachelor Degree 0.0
income:UNKNOWN 0.0
income:Less than $20K 0.0
income:$151K+ 0.0
income:$41K - $60K 0.0
income:$101K - $150K 0.0
income:$61K - $80K 0.0
age:35-44 0.0
age:18-24 0.0
HS_TRAVEL_BUSINESS 0.0
VALUE_HUNTER 0.0
ONLINE_PURCHASER 0.0
MAGAZINE_READER 0.0
LT_EXERCISE_WALKING_V2 0.0
LT_EXERCISE_PILATES_BARRE_V2 0.0
ETHNICSD_V2:Other 0.0
CHILDREN_AGED_3_5 0.0
REGB_FINTECH_MWALLET 0.0
SOCIALSD_LINKEDIN_V2 0.0
PRESENCE_OF_CC 0.0
OS_FIN_PLANNING 0.0
TV_STREAMING_SERV_MANY 0.0
SOCIALSD_SNAPCHAT 0.0
SOCIALSD_TRIP_ADVISOR 0.0
SOCIALSD_TUMBLR 0.0
CC_USER 0.0
CC_NEW_ISSUE 0.0
SOCIALSD_TWITTER 0.0
LT_PET_OWNER_V2 0.0
LT_CAT_OWNER_V2 0.0
TV_FAVORITES_LIVE_SPORTS 0.0
CHILDREN_AGED_11_15 0.0
CHILDREN_AGED_0_2 0.0
TV_FAVORITES_NEWS 0.0
SOCIALSD_FACEBOOK_V2 0.0
EXERCISE_AEROBIC_V2 0.0
OS_FIN_IMPCONTROL 0.0
EXERCISE_FAN_V2 0.0
CHANNELSD_BANNER_SCALE 0.0
LT_TV_DAILY_VIEWING_V2 0.0
EXERCISE_YOGA_V2 0.0
EXERCISE_WALKING_V2 0.0
EXERCISE_RUNNING_JOGGING_V2 0.0
CHANNELSD_INTERTV_SCALE 0.0
SMARTPHONE_ANDROID_SCALE 0.0
AUTOMOTIVE_BUFF_V2 0.0
AUTO_AVG_MILEAGE 0.0
SMARTPHONE_NONE_SCALE 0.0
EXERCISE_PILATES_BARRE_V2 0.0
REGB_CC_AIRLINE_IM 9.535496464351328e-10
JOBSSD_BLUE_COLLAR 4.654868002776569e-08
HW_JUNK_DIET 1.0931858715902873e-07
LT_HOME_FURNISHINGS_DECO_V2 1.5693859215175993e-07
OS_COOKING 1.7509355291674694e-07
OS_LAGGARD 2.2335335775099783e-07
SMARTPHONE_IPHONE_SCALE 2.7949486456550793e-07
age:UNKNOWN 3.6852176090544233e-07
JEWELRY_PURCHASER 5.255301608255604e-07
SD_BUSINESS_OWNER_V2 5.518013669080224e-07
TV_VIEWER_EMPATHIZER 5.579904433610169e-07
income:$21K - $40K 5.779075971737485e-07
LT_TRAVEL_DOMESTIC_V2 6.16355449664517e-07
income:$81K - $100K 7.313236449157205e-07
age:65+ 1.0932633620353603e-06
ZIPCAR_USER 1.1291697517469338e-06
ETHNICSD_V2:Middle Eastern 1.1333609169250831e-06
YOUNG_ADULT_IN_HH 1.133502423422809e-06
AUTO_AGE 1.1448424613786375e-06
Education:Less Than HS 1.1548658813516802e-06
HOME_DECORATING_FAN_V2 1.1717799310581398e-06
SPEC_SPORT_AUTO_MC_V2 1.1717799310581398e-06
age:25-34 1.1717799310581398e-06
INMARKET_TERM_LIFE 1.1717799310581398e-06
JOBSSD_SALES 1.1717799310581398e-06
CHILDREN_AGED_16_17 1.1717799310581398e-06
Education:Graduate Degree 1.179657378543005e-06
TRAVELPROP_DOMESTIC 1.2142532796212548e-06
ETHNICSD_V2:Hispanic 1.5623732414108528e-06
SD_GENDER:Inferred Female 1.5623732414108528e-06
LT_HOME_GARDEN_V2 1.5623732414108528e-06
TV_FAVORITES_HOME_IMP 1.6275440589393195e-06
HW_SMOKING 1.7576698965872096e-06
HW_DIET 1.7576698965872096e-06
INMARKET_VENMO 1.7576698965872096e-06
OS_FOODIE 1.7576698965872096e-06
SD_EMPLOYMENT 1.874847889693023e-06
age:45-54 1.874847889693023e-06
LT_FISHING_FAN_V2 1.874847889693023e-06
JOB_SEEKER_ACTIVE 2.050614879351744e-06
age:55-64 2.050614879351744e-06
LT_EXERCISE_FAN_V2 2.0831643218811373e-06
CHILDREN_AGED_6_10 2.109203875904652e-06
PREMOVER_V2 2.1425887278549043e-06
LT_DOG_OWNER_V2 2.259819397765091e-06
LT_TEAM_SPORTS_V2 2.3435598621162796e-06
REGB_FINTECH_DIGITAL 2.417711477678231e-06
JOBSSD_HOMEMAKER 2.782225379039273e-06
SOCIALSD_INSTAGRAM_V2 2.8122718345395353e-06
TV_CABLE_V2 2.9870568857085455e-06
LT_SENIOR_ADULT_IN_HH_V2 3.012053535700126e-06
OS_VALUE_SEEKER 3.1247464828217056e-06
YOUTUBE_CREATOR 3.222394810409884e-06
HOME_PURCHASE_PRICE 3.3744354629621087e-06
LT_HUNTING_FAN_V2 3.4134458861258856e-06
HW_JOB_SATIS 3.4910093145271376e-06
SPENDEX_TRAVEL_DOM_V2 3.728465282003478e-06
HW_SLEEP_V3 3.984051765597675e-06
LT_EXERCISE 4.017531192199335e-06
LT_COUPONER 4.355650214178967e-06
HW_STRESS_V2 4.451032043541533e-06
TRAVELPROP_INTL 5.425563715358492e-06
SPENDEX_TRAVEL_INTL_V2 5.463800680833132e-06
SOCIALSD_PINTEREST 5.882999250178524e-06
SOCIALSD_DEAL_SITE 6.151844638055234e-06
SD_LOR_V2 6.518520806906385e-06
LT_GOLF_FAN_V2 7.78713228284329e-06
HW_YOGAPILATE 8.445152277831672e-06
SPENDEX_PERSONAL_V2 2.1350000582049102e-05
SPENDEX_TRAVEL_CRUISE_V2 5.782864354687759e-05
SPENDEX_EDUCATION_V2 0.00017133038710668956
CHANGE_IN_INCOME_12MO 0.00037192186911974264
SPENDEX_TRAVEL_V2 0.0008941242385572665
SPENDEX_APPAREL_V2 0.0017228414328814084
SPENDEX_PLUS_V2 0.08133338946556545
ZIP5 0.9152752206877892

In [ ]:
# GAP

In [51]:
## CLUSTER 4

# Preparing file for cluster_4 prediction

# First make predictions using the decision tree for Cluster 5
predictions5 = dt.predict(features_no02) 
df_comb3_no02['predictions5'] = predictions5
df_comb3_no02

,REC_ID,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,...,ETHNICSD_V2:Unknown,ETHNICSD_V2:Native Amer/Pac Island,ETHNICSD_V2:Other,cluster_0,cluster_2,cluster_5,cluster_3,cluster_4,cluster_1,predictions5
11,IND_000032374,60025,7,3,0,3,1,3,1,7,...,0,0,0,0,0,1,0,0,0,1
15,IND_000035522,94123,7,2,0,3,3,3,2,7,...,0,0,0,0,0,0,1,0,0,0
22,IND_000036727,60010,7,4,0,5,2,2,1,5,...,0,0,0,0,0,0,1,0,0,0
27,IND_004561271,60712,4,5,0,2,4,2,4,7,...,0,0,0,0,0,1,0,0,0,1
28,IND_004562054,95014,7,3,0,3,5,2,1,7,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8177198,IND_003772879,60565,6,7,1,2,4,1,4,7,...,0,0,0,0,0,1,0,0,0,1
8177205,IND_001414864,95123,7,3,0,6,2,2,2,7,...,0,0,0,0,0,0,0,1,0,0
8177207,IND_007674098,60007,6,1,0,3,4,5,2,6,...,0,0,0,0,0,1,0,0,0,1
8177210,IND_007676031,95118,6,4,0,7,7,2,4,7,...,0,0,0,0,0,0,0,1,0,0
8177212,IND_007676373,60448,6,2,0,1,1,4,1,7,...,0,0,0,0,0,1,0,0,0,1

In [53]:
#drop columns 
df_comb3_no025 = df_comb3_no02[df_comb3_no02["predictions5"] < 0.5].drop("predictions5", axis=1)

In [54]:
#Preview
df_comb3_no025

,REC_ID,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,...,ETHNICSD_V2:Middle Eastern,ETHNICSD_V2:Unknown,ETHNICSD_V2:Native Amer/Pac Island,ETHNICSD_V2:Other,cluster_0,cluster_2,cluster_5,cluster_3,cluster_4,cluster_1
15,IND_000035522,94123,7,2,0,3,3,3,2,7,...,0,0,0,0,0,0,0,1,0,0
22,IND_000036727,60010,7,4,0,5,2,2,1,5,...,0,0,0,0,0,0,0,1,0,0
28,IND_004562054,95014,7,3,0,3,5,2,1,7,...,0,0,0,0,0,0,0,0,1,0
30,IND_004563713,94598,6,2,0,3,2,4,2,6,...,0,0,0,0,0,0,0,1,0,0
68,IND_001838144,94134,7,3,0,4,7,2,4,6,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8177165,IND_000881815,94545,6,4,0,3,7,2,3,7,...,0,0,0,0,0,0,0,0,1,0
8177180,IND_010643206,94131,7,5,0,4,5,2,3,7,...,0,0,0,0,0,0,0,1,0,0
8177183,IND_010644408,94112,6,3,0,5,4,3,2,6,...,0,0,0,0,0,0,0,0,1,0
8177205,IND_001414864,95123,7,3,0,6,2,2,2,7,...,0,0,0,0,0,0,0,0,1,0
8177210,IND_007676031,95118,6,4,0,7,7,2,4,7,...,0,0,0,0,0,0,0,0,1,0

In [55]:
# Model building for cluster_4

# Create a dataframe with just the features without cluster 0 
features_no025 = df_comb3_no025.drop(['REC_ID', 'cluster_0', 'cluster_1', 'cluster_2', 'cluster_3', 'cluster_4', 'cluster_5'], axis = 1)
features_no025

,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,SMARTPHONE_NONE_SCALE,...,ETHNICSD_V2:Hispanic,ETHNICSD_V2:Asian-Other,ETHNICSD_V2:Asian-Chinese,ETHNICSD_V2:Asian-Indian,ETHNICSD_V2:AA,ETHNICSD_V2:Caucasian-Jewish,ETHNICSD_V2:Middle Eastern,ETHNICSD_V2:Unknown,ETHNICSD_V2:Native Amer/Pac Island,ETHNICSD_V2:Other
15,94123,7,2,0,3,3,3,2,7,3,...,0,0,0,0,0,0,0,0,0,0
22,60010,7,4,0,5,2,2,1,5,3,...,0,0,0,0,0,0,0,0,0,0
28,95014,7,3,0,3,5,2,1,7,4,...,1,0,0,0,0,0,0,0,0,0
30,94598,6,2,0,3,2,4,2,6,5,...,0,0,0,0,0,1,0,0,0,0
68,94134,7,3,0,4,7,2,4,6,2,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8177165,94545,6,4,0,3,7,2,3,7,3,...,0,0,0,0,0,0,0,0,0,0
8177180,94131,7,5,0,4,5,2,3,7,2,...,0,0,0,0,0,0,0,0,0,0
8177183,94112,6,3,0,5,4,3,2,6,1,...,1,0,0,0,0,0,0,0,0,0
8177205,95123,7,3,0,6,2,2,2,7,4,...,0,0,0,0,0,0,0,0,0,0
8177210,95118,6,4,0,7,7,2,4,7,3,...,0,0,0,0,0,0,0,0,0,0

In [56]:
# Let's start with Logistic again
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no025
y = df_comb3_no025['cluster_4']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a logistic regression model
logreg = LogisticRegression(random_state=42)

# Train the model on the training data
logreg.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = logreg.predict(X_test)

# Evaluate the performance of the model
accuracy = logreg.score(X_test, y_test)
print("Accuracy:", accuracy)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

Accuracy: 0.9957024617996605

In [57]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[ 81312    430]
 [   380 106358]]

In [58]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no025
y = df_comb3_no025['cluster_4']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a random forest classifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the training data
rf.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = rf.predict(X_test)

# Evaluate the performance of the model
accuracy = rf.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9990662139219015

In [59]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[ 81650     92]
 [    84 106654]]

In [60]:
import numpy as np

# Get the feature importances 
importances = rf.feature_importances_ 

# Get the indices that would sort the importances in ascending order
sorted_indices = np.argsort(importances)
# Print the feature importances in ascending order
for feature, importance in zip(X.columns[sorted_indices], importances[sorted_indices]):
   print(feature, importance)

income:UNKNOWN 1.0762809432520718e-07
PREMOVER_NEW_OWNER_V2 1.301491716632346e-07
ETHNICSD_V2:Other 1.6829003710355646e-07
Education:Less Than HS 4.890611562781188e-06
SD_GENDER:Unknown 4.900171898918775e-06
SPEC_SPORT_AUTO_MC_V2 5.046138490579147e-06
income:Less than $20K 6.3302921002386785e-06
ETHNICSD_V2:Native Amer/Pac Island 6.645205363660288e-06
SD_GENDER:Inferred Female 7.01165001661893e-06
income:$61K - $80K 7.470613593761491e-06
ETHNICSD_V2:AA 7.801744548466284e-06
ETHNICSD_V2:Middle Eastern 8.419228161731992e-06
CC_NEW_ISSUE 8.452331072231207e-06
TEAM_SPORTS_V2 8.676481835567603e-06
age:18-24 9.541886594552965e-06
APPAREL_WOMEN_PLUS_V2 9.797352261288186e-06
VALUE_HUNTER 1.0491417022360703e-05
GAMING_SPORTSBOOK_V2 1.1418428653335656e-05
age:25-34 1.1616536398120305e-05
GAMING_FANTASY_SPORTS_V2 1.2563168534280434e-05
EXERCISE_PILATES_BARRE_V2 1.275414252233101e-05
income:$41K - $60K 1.275829565780894e-05
ETHNICSD_V2:Asian-Other 1.2834976243134261e-05
CHILDREN_AGED_0_2 1.2855333105786264e-05
SD_GENDER:Inferred Male 1.2906781679820633e-05
income:$81K - $100K 1.3135524090370107e-05
SD_GENDER:Female 1.3255332538561367e-05
JOB_SEEKER_ACTIVE 1.4239813357365238e-05
JOB_SEEKER 1.4355544965148658e-05
EXERCISE_RUNNING_JOGGING_V2 1.528473933519539e-05
PARENTING_CATEGORY 1.6164931469113067e-05
JEWELRY_PURCHASER 1.7331204586464103e-05
EXERCISE_YOGA_V2 1.7486890729332298e-05
LT_DEAL_SITE 1.813117344918276e-05
age:45-54 1.87017384560198e-05
age:UNKNOWN 1.886775836215339e-05
SD_GENDER:Male 1.8977540374129105e-05
AUTOMOTIVE_BUFF_V2 1.9827653022557753e-05
ETHNICSD_V2:Unknown 2.0705119549339164e-05
Education:HS Degree 2.1933875450813894e-05
EXERCISE_FAN_V2 2.2139362060692055e-05
Education:Bachelor Degree 2.24297867726406e-05
Education:Graduate Degree 2.3871183729693666e-05
ETHNICSD_V2:Caucasian-Jewish 2.3988899410356486e-05
CHILDREN_AGED_3_5 2.412059295114239e-05
ETHNICSD_V2:Asian-Indian 2.4281984377251638e-05
HOME_DECORATING_FAN_V2 2.4675548074338067e-05
age:55-64 2.4953613018735772e-05
MAGAZINE_READER 2.5393994796171276e-05
CHILDREN_AGED_6_10 2.6555238084979997e-05
CHILDREN_AGED_16_17 2.826353621177575e-05
age:35-44 2.8286756541244978e-05
EXERCISE_WALKING_V2 2.9220554139859522e-05
OUTDOOR_GROUPING_V2 3.991367686667884e-05
YOUNG_ADULT_IN_HH 4.5491720763083544e-05
CHILDREN_AGED_11_15 4.615870663116257e-05
INMARKET_VENMO 5.4414523541321764e-05
HEALTH_BEAUTY 5.863726044066084e-05
LT_GAMING_FANTASY_SPORTS_V2 6.140171620566589e-05
LT_SPEC_SPORT_AUTO_MC_V2 6.185833918473672e-05
SD_EMPLOYMENT 6.192283853563864e-05
YOUTUBE_CREATOR 6.327686810553531e-05
LT_FISHING_FAN_V2 6.705539896633209e-05
LT_GAMING_SPORTSBOOK_V2 6.956075423871156e-05
LT_EXERCISE_FAN_V2 7.077700285443386e-05
LT_EXERCISE_PILATES_BARRE_V2 7.127357977654564e-05
LT_TEAM_SPORTS_V2 7.17869696388822e-05
TV_FAVORITES_HOME_IMP 7.331605804088353e-05
TV_CABLE_V2 7.350929841654933e-05
LT_PET_OWNER_V2 7.53650889834651e-05
LT_HUNTING_SHOOTING_FAN_V2 7.59637239099936e-05
SOCIALSD_PINTEREST 7.622862525904365e-05
LT_HUNTING_FAN_V2 7.810552449953777e-05
LT_GOLF_FAN_V2 7.813117166904694e-05
HW_YOGAPILATE 7.889027379006608e-05
LT_HOME_FURNISHINGS_DECO_V2 8.032366615635893e-05
BEAUTY_COSMETICS 8.923128872173153e-05
LT_COUPONER 8.998162963186214e-05
LT_CAMPING_FAN_V2 9.030804683145912e-05
HW_JOB_SATIS 9.081712002366812e-05
TV_FAVORITES_NEWS 9.420506564846724e-05
AUTO_AVG_MILEAGE 9.442743573738625e-05
HW_JUNK_DIET 9.456917429147399e-05
JOBSSD_STUDENT 9.499713775810229e-05
LT_EXERCISE_WALKING_V2 9.539730621565945e-05
INMARKET_ONLINEDATE 9.817389323746831e-05
REGB_FINTECH_DIGITAL 9.8240832163604e-05
OS_VALUE_SEEKER 9.850180177887095e-05
HW_SMOKING 9.887484964325425e-05
REGB_FINTECH_MWALLET 9.910867319920791e-05
SOCIALSD_TRIP_ADVISOR 0.00010016205924872539
ONLINE_PURCHASER 0.00010090497479294144
HW_SLEEP_V3 0.00010348874957044248
OS_RISKTAKING_FIN 0.00010560470826614493
EXERCISE_AEROBIC_V2 0.00010634595078978184
SOCIALSD_TUMBLR 0.00011192209053974691
INMARKET_TERM_LIFE 0.00011211088064407457
TV_FAVORITES_LIVE_SPORTS 0.00011549370927501658
SOCIALSD_DEAL_SITE 0.00011805153786326609
HW_DIET 0.00011832737763673335
INMARKET_PAYPAL 0.00012285290490032005
CHANNELSD_INTERTV_SCALE 0.00012498661910965295
OS_INNOVATOR 0.00012981632569720742
OS_LAGGARD 0.00013452834235088193
LT_HOME_IMPROVEMENT_V2 0.00013628607704212458
ZIPCAR_USER 0.0001369436760219752
TV_VIEWER_EMPATHIZER 0.0001384741669663135
SMARTPHONE_NONE_SCALE 0.00014364773931427346
JOBSSD_MIDDLE_MGMT 0.00014827878036884407
OS_FIN_IMPCONTROL 0.00015478512844284428
SMARTPHONE_IPHONE_SCALE 0.00016410872384596352
OS_MATERIALISM 0.0001673065314225674
UBER_LYFT_USER 0.000177522220290806
HW_STRESS_V2 0.00017944648063093955
TV_STREAMING_SERV_MANY 0.00018129572953571818
LT_HOME_GARDEN_V2 0.000188294110684508
LT_DOG_OWNER_V2 0.00018860300883188845
income:$21K - $40K 0.00019051178845849454
SD_BUSINESS_OWNER_V2 0.00021242390708560023
SOCIALSD_INSTAGRAM_V2 0.00021459405093157135
OS_FOODIE 0.00022393593390808867
ETHNICSD_V2:Asian-Chinese 0.0002356957283106224
JOBSSD_SALES 0.0002423744526064299
HS_TRAVEL_BUSINESS 0.00025207651736121545
AUTO_AGE 0.0002631831972244618
INMARKET_ONLINEEDU_V2 0.0002649468035884679
PREMOVER_V2 0.000281470393159353
income:$101K - $150K 0.00028174398180376805
SD_LOR_V2 0.0003200599764080577
JOBSSD_RETIRED 0.0003597566416963501
SOCIALSD_TWITTER 0.00037010052900437475
LT_CAT_OWNER_V2 0.00039317330745759305
SOCIALSD_SNAPCHAT 0.0004335406557146866
CHANNELSD_BANNER_SCALE 0.00044895687930948083
JOBSSD_HOMEMAKER 0.0004544418524357552
LT_TV_DAILY_VIEWING_V2 0.00046232019333764885
LT_SENIOR_ADULT_IN_HH_V2 0.0004742594628970374
JOBSSD_CORP_LEADER 0.0005160527117162409
SMARTPHONE_ANDROID_SCALE 0.0005231227695824426
JOBSSD_BLUE_COLLAR 0.0006097326000433385
ETHNICSD_V2:Hispanic 0.000655167308009729
age:65+ 0.0007360826185066854
income:$151K+ 0.0008875397553057279
REGB_CC_AIRLINE_IM 0.0011172350053468693
LT_TRAVEL_DOMESTIC_V2 0.0011248425012368507
LT_EXERCISE 0.0012952909070223584
SOCIALSD_LINKEDIN_V2 0.0013051735628350227
PRESENCE_OF_CC 0.00160025054718309
ETHNICSD_V2:Caucasian-Other 0.0016077216072511696
HOME_PURCHASE_PRICE 0.0017360380360060517
CC_USER 0.0017758431004826483
SOCIALSD_FACEBOOK_V2 0.0017933965572596124
OS_FIN_PLANNING 0.0019621497475990094
TRAVELPROP_INTL 0.0027452636118363988
TRAVELPROP_DOMESTIC 0.0030661853573888116
CHANGE_IN_INCOME_12MO 0.00470618987693083
OS_COOKING 0.007280291975250772
ZIP5 0.00898141110211941
SPENDEX_TRAVEL_CRUISE_V2 0.013943368659835887
SPENDEX_TRAVEL_DOM_V2 0.031406501389416405
SPENDEX_TRAVEL_INTL_V2 0.043410224061046714
SPENDEX_TRAVEL_V2 0.0938503788429531
SPENDEX_PERSONAL_V2 0.1524290180300319
SPENDEX_EDUCATION_V2 0.1817874594927643
SPENDEX_APPAREL_V2 0.20780082432806762
SPENDEX_PLUS_V2 0.2156057232943066

In [61]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no025
y = df_comb3_no025['cluster_4']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a decision tree classifier
dt = DecisionTreeClassifier(random_state=42)

# Train the classifier on the training data
dt.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = dt.predict(X_test)

# Evaluate the performance of the model
accuracy = dt.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9993951612903226

In [62]:
from pandas._libs.tslibs import dtypes
import numpy as np
# Get the feature importances 
importances = dt.feature_importances_ 

# Get the indices that would sort the importances in ascending order
sorted_indices = np.argsort(importances)
# Print the feature importances in ascending order
for feature, importance in zip(X.columns[sorted_indices], importances[sorted_indices]):
   print(feature, importance)

ETHNICSD_V2:Other 0.0
LT_EXERCISE_WALKING_V2 0.0
LT_EXERCISE_PILATES_BARRE_V2 0.0
JEWELRY_PURCHASER 0.0
LT_EXERCISE 0.0
HW_YOGAPILATE 0.0
LT_COUPONER 0.0
LT_HOME_GARDEN_V2 0.0
ETHNICSD_V2:Caucasian-Other 0.0
HEALTH_BEAUTY 0.0
HW_JUNK_DIET 0.0
HW_DIET 0.0
EXERCISE_YOGA_V2 0.0
EXERCISE_WALKING_V2 0.0
EXERCISE_RUNNING_JOGGING_V2 0.0
EXERCISE_PILATES_BARRE_V2 0.0
ONLINE_PURCHASER 0.0
EXERCISE_AEROBIC_V2 0.0
ETHNICSD_V2:Hispanic 0.0
MAGAZINE_READER 0.0
PREMOVER_NEW_OWNER_V2 0.0
INMARKET_ONLINEDATE 0.0
APPAREL_WOMEN_PLUS_V2 0.0
SPEC_SPORT_AUTO_MC_V2 0.0
TEAM_SPORTS_V2 0.0
JOB_SEEKER 0.0
LT_GAMING_FANTASY_SPORTS_V2 0.0
LT_FISHING_FAN_V2 0.0
ETHNICSD_V2:Native Amer/Pac Island 0.0
HOME_DECORATING_FAN_V2 0.0
GAMING_SPORTSBOOK_V2 0.0
JOB_SEEKER_ACTIVE 0.0
BEAUTY_COSMETICS 0.0
ZIPCAR_USER 0.0
UBER_LYFT_USER 0.0
SD_GENDER:Inferred Female 0.0
SD_GENDER:Inferred Male 0.0
income:UNKNOWN 0.0
LT_DEAL_SITE 0.0
INMARKET_VENMO 0.0
JOBSSD_STUDENT 0.0
INMARKET_PAYPAL 0.0
PARENTING_CATEGORY 0.0
LT_TRAVEL_DOMESTIC_V2 0.0
VALUE_HUNTER 0.0
PRESENCE_OF_CC 0.0
income:$61K - $80K 0.0
SOCIALSD_TRIP_ADVISOR 0.0
SOCIALSD_SNAPCHAT 0.0
ETHNICSD_V2:Caucasian-Jewish 0.0
SOCIALSD_LINKEDIN_V2 0.0
SOCIALSD_INSTAGRAM_V2 0.0
SOCIALSD_FACEBOOK_V2 0.0
ETHNICSD_V2:Middle Eastern 0.0
income:$81K - $100K 0.0
income:$21K - $40K 0.0
income:$101K - $150K 0.0
income:$41K - $60K 0.0
income:$151K+ 0.0
ETHNICSD_V2:Unknown 0.0
AUTOMOTIVE_BUFF_V2 0.0
AUTO_AVG_MILEAGE 0.0
income:Less than $20K 0.0
age:55-64 0.0
REGB_CC_AIRLINE_IM 0.0
ETHNICSD_V2:AA 0.0
LT_DOG_OWNER_V2 0.0
OS_FIN_PLANNING 0.0
SD_GENDER:Female 0.0
SD_GENDER:Male 0.0
CC_USER 0.0
CC_NEW_ISSUE 0.0
Education:Less Than HS 0.0
ETHNICSD_V2:Asian-Chinese 0.0
Education:Bachelor Degree 0.0
age:UNKNOWN 0.0
age:18-24 0.0
OUTDOOR_GROUPING_V2 0.0
CHILDREN_AGED_3_5 0.0
CHILDREN_AGED_16_17 0.0
CHILDREN_AGED_11_15 0.0
CHILDREN_AGED_0_2 0.0
YOUTUBE_CREATOR 0.0
age:25-34 0.0
age:45-54 0.0
CHILDREN_AGED_6_10 0.0
SOCIALSD_TWITTER 6.977965461133001e-07
TRAVELPROP_INTL 8.089351368214356e-07
PREMOVER_V2 2.5012207846794444e-06
LT_GAMING_SPORTSBOOK_V2 2.52703983794065e-06
TV_FAVORITES_HOME_IMP 2.654338996193724e-06
Education:Graduate Degree 2.701318447453802e-06
SMARTPHONE_ANDROID_SCALE 2.701318447453802e-06
GAMING_FANTASY_SPORTS_V2 2.701318447453802e-06
INMARKET_TERM_LIFE 2.701318447453802e-06
LT_TV_DAILY_VIEWING_V2 3.6017579299384025e-06
SD_EMPLOYMENT 3.6017579299384025e-06
SMARTPHONE_NONE_SCALE 3.994158100582057e-06
OS_LAGGARD 4.051977671180703e-06
TV_CABLE_V2 4.322109515926083e-06
JOBSSD_MIDDLE_MGMT 4.322109515926083e-06
TV_STREAMING_SERV_MANY 4.604520080887164e-06
LT_HUNTING_FAN_V2 4.727307283044153e-06
OS_FOODIE 4.727307283044153e-06
LT_PET_OWNER_V2 4.830929286980879e-06
OS_MATERIALISM 4.862373205416845e-06
HS_TRAVEL_BUSINESS 4.862373205416845e-06
age:35-44 5.016734259557062e-06
LT_CAT_OWNER_V2 5.025765686170725e-06
OS_VALUE_SEEKER 5.0649720889758795e-06
HW_JOB_SATIS 5.192886664570529e-06
YOUNG_ADULT_IN_HH 5.248275840767387e-06
SMARTPHONE_IPHONE_SCALE 5.352612479214024e-06
OS_COOKING 5.541166046059081e-06
CHANNELSD_INTERTV_SCALE 5.876125473576402e-06
JOBSSD_RETIRED 6.545983794727341e-06
OS_RISKTAKING_FIN 6.685763157448155e-06
age:65+ 6.753296118634505e-06
ETHNICSD_V2:Asian-Other 7.590142870092855e-06
OS_FIN_IMPCONTROL 7.76629053642968e-06
ETHNICSD_V2:Asian-Indian 7.803808848199874e-06
LT_HOME_FURNISHINGS_DECO_V2 8.103955342361406e-06
Education:HS Degree 8.152193171780224e-06
OS_INNOVATOR 8.171488303547748e-06
HW_SMOKING 8.838042445878515e-06
JOBSSD_BLUE_COLLAR 8.840678555303351e-06
TV_VIEWER_EMPATHIZER 8.840678555303351e-06
LT_TEAM_SPORTS_V2 9.238713735628928e-06
JOBSSD_CORP_LEADER 9.261663248413036e-06
SD_BUSINESS_OWNER_V2 9.9271682569869e-06
SD_GENDER:Unknown 9.927168256986902e-06
REGB_FINTECH_MWALLET 1.0124954780558594e-05
AUTO_AGE 1.0179511912685295e-05
LT_HOME_IMPROVEMENT_V2 1.0302702915870313e-05
JOBSSD_SALES 1.1090461598916262e-05
LT_HUNTING_SHOOTING_FAN_V2 1.1171659510274465e-05
REGB_FINTECH_DIGITAL 1.1804080610722494e-05
SOCIALSD_TUMBLR 1.1836040039501528e-05
HOME_PURCHASE_PRICE 1.200585976646134e-05
LT_SPEC_SPORT_AUTO_MC_V2 1.2508024021302943e-05
LT_SENIOR_ADULT_IN_HH_V2 1.3097301563412374e-05
INMARKET_ONLINEEDU_V2 1.3454775692215542e-05
HW_STRESS_V2 1.3841041187906149e-05
EXERCISE_FAN_V2 1.4157364408701064e-05
LT_GOLF_FAN_V2 1.4601490229293394e-05
JOBSSD_HOMEMAKER 1.4928338788560492e-05
LT_EXERCISE_FAN_V2 1.5992350929824986e-05
LT_CAMPING_FAN_V2 1.600210654549374e-05
TV_FAVORITES_LIVE_SPORTS 1.655984017793304e-05
TV_FAVORITES_NEWS 1.7942724796357547e-05
SOCIALSD_PINTEREST 1.866235493390893e-05
SD_LOR_V2 2.382947220616049e-05
SPENDEX_EDUCATION_V2 2.5138208521743603e-05
HW_SLEEP_V3 2.644891346397012e-05
CHANNELSD_BANNER_SCALE 2.6710760300923148e-05
SOCIALSD_DEAL_SITE 2.780428487700663e-05
SPENDEX_TRAVEL_INTL_V2 0.00010308536324045797
CHANGE_IN_INCOME_12MO 0.00011628618303810795
SPENDEX_APPAREL_V2 0.00022014310364024136
SPENDEX_PERSONAL_V2 0.0006064591277569974
SPENDEX_TRAVEL_CRUISE_V2 0.0006221789107839558
TRAVELPROP_DOMESTIC 0.0007033457850788427
SPENDEX_TRAVEL_DOM_V2 0.0007695080375352439
ZIP5 0.00850606732252345
SPENDEX_TRAVEL_V2 0.012375458716668382
SPENDEX_PLUS_V2 0.9753300039661181

In [63]:
#confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[ 81672     70]
 [    44 106694]]

In [64]:
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split

# Load the data into a pandas dataframe

# Split the data into training and testing sets
X = features_no025
y = df_comb3_no025['cluster_4']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Set up the XGBoost model
params = {'objective': 'binary:logistic', 'eval_metric': 'auc'}
num_rounds = 10
early_stopping_rounds = 50
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# Train the model
modelxgb = xgb.train(params, dtrain, num_rounds, evals=[(dtest, 'test')], early_stopping_rounds=early_stopping_rounds)

# Make predictions on the test set
y_pred = model.predict(dtest)

# Calculate the accuracy score
threshold = 0.5
y_pred_binary = [1 if p > threshold else 0 for p in y_pred]
accuracy = sum(y_pred_binary == y_test) / len(y_test)
print('Accuracy: %.2f%%' % (accuracy * 100.0))

[0]	test-auc:0.99994
[1]	test-auc:0.99994
[2]	test-auc:0.99996
[3]	test-auc:0.99996
[4]	test-auc:0.99997
[5]	test-auc:0.99997
[6]	test-auc:0.99997
[7]	test-auc:0.99997
[8]	test-auc:0.99997
[9]	test-auc:0.99997
Accuracy: 43.43%

In [65]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_binary)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[122776      1]
 [159939      4]]

In [ ]:
# GAP

In [66]:
## CLUSTER 3

# Preparing file for cluster_3 prediction

# First make predictions using the decision tree for Cluster 4
predictions4 = dt.predict(features_no025) 
df_comb3_no025['predictions4'] = predictions4
df_comb3_no025

,REC_ID,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,...,ETHNICSD_V2:Unknown,ETHNICSD_V2:Native Amer/Pac Island,ETHNICSD_V2:Other,cluster_0,cluster_2,cluster_5,cluster_3,cluster_4,cluster_1,predictions4
15,IND_000035522,94123,7,2,0,3,3,3,2,7,...,0,0,0,0,0,0,1,0,0,0
22,IND_000036727,60010,7,4,0,5,2,2,1,5,...,0,0,0,0,0,0,1,0,0,0
28,IND_004562054,95014,7,3,0,3,5,2,1,7,...,0,0,0,0,0,0,0,1,0,1
30,IND_004563713,94598,6,2,0,3,2,4,2,6,...,0,0,0,0,0,0,1,0,0,0
68,IND_001838144,94134,7,3,0,4,7,2,4,6,...,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8177165,IND_000881815,94545,6,4,0,3,7,2,3,7,...,0,0,0,0,0,0,0,1,0,1
8177180,IND_010643206,94131,7,5,0,4,5,2,3,7,...,0,0,0,0,0,0,1,0,0,0
8177183,IND_010644408,94112,6,3,0,5,4,3,2,6,...,0,0,0,0,0,0,0,1,0,1
8177205,IND_001414864,95123,7,3,0,6,2,2,2,7,...,0,0,0,0,0,0,0,1,0,1
8177210,IND_007676031,95118,6,4,0,7,7,2,4,7,...,0,0,0,0,0,0,0,1,0,1

In [67]:
#drop columns 
df_comb3_no0254 = df_comb3_no025[df_comb3_no025["predictions4"] < 0.5].drop("predictions4", axis=1)

In [68]:
#Preview
df_comb3_no0254

,REC_ID,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,...,ETHNICSD_V2:Middle Eastern,ETHNICSD_V2:Unknown,ETHNICSD_V2:Native Amer/Pac Island,ETHNICSD_V2:Other,cluster_0,cluster_2,cluster_5,cluster_3,cluster_4,cluster_1
15,IND_000035522,94123,7,2,0,3,3,3,2,7,...,0,0,0,0,0,0,0,1,0,0
22,IND_000036727,60010,7,4,0,5,2,2,1,5,...,0,0,0,0,0,0,0,1,0,0
30,IND_004563713,94598,6,2,0,3,2,4,2,6,...,0,0,0,0,0,0,0,1,0,0
94,IND_001847572,94558,7,1,0,4,4,5,1,6,...,0,0,0,0,0,0,0,1,0,0
146,IND_005727399,95127,7,4,0,3,7,2,3,7,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8177094,IND_003332614,95030,6,6,1,2,5,2,2,7,...,0,0,0,0,0,0,0,0,0,1
8177095,IND_003332632,95148,7,2,1,6,5,6,2,7,...,0,1,0,0,0,0,0,1,0,0
8177096,IND_003334437,94708,6,3,0,5,4,2,4,7,...,0,0,0,0,0,0,0,1,0,0
8177108,IND_006638002,94118,7,4,0,4,5,2,4,7,...,0,0,0,0,0,0,0,1,0,0
8177180,IND_010643206,94131,7,5,0,4,5,2,3,7,...,0,0,0,0,0,0,0,1,0,0

In [69]:
# Model building for cluster_3

# Create a dataframe with just the features without cluster 0 
features_no0254 = df_comb3_no0254.drop(['REC_ID', 'cluster_0', 'cluster_1', 'cluster_2', 'cluster_3', 'cluster_4', 'cluster_5'], axis = 1)
features_no0254

,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,SMARTPHONE_NONE_SCALE,...,ETHNICSD_V2:Hispanic,ETHNICSD_V2:Asian-Other,ETHNICSD_V2:Asian-Chinese,ETHNICSD_V2:Asian-Indian,ETHNICSD_V2:AA,ETHNICSD_V2:Caucasian-Jewish,ETHNICSD_V2:Middle Eastern,ETHNICSD_V2:Unknown,ETHNICSD_V2:Native Amer/Pac Island,ETHNICSD_V2:Other
15,94123,7,2,0,3,3,3,2,7,3,...,0,0,0,0,0,0,0,0,0,0
22,60010,7,4,0,5,2,2,1,5,3,...,0,0,0,0,0,0,0,0,0,0
30,94598,6,2,0,3,2,4,2,6,5,...,0,0,0,0,0,1,0,0,0,0
94,94558,7,1,0,4,4,5,1,6,7,...,0,0,0,0,0,0,0,0,0,0
146,95127,7,4,0,3,7,2,3,7,2,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8177094,95030,6,6,1,2,5,2,2,7,3,...,0,0,0,0,0,0,0,0,0,0
8177095,95148,7,2,1,6,5,6,2,7,2,...,0,0,0,0,0,0,0,1,0,0
8177096,94708,6,3,0,5,4,2,4,7,2,...,1,0,0,0,0,0,0,0,0,0
8177108,94118,7,4,0,4,5,2,4,7,2,...,0,0,0,0,0,0,0,0,0,0
8177180,94131,7,5,0,4,5,2,3,7,2,...,0,0,0,0,0,0,0,0,0,0

In [70]:
# Let's start with Logistic again
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no0254
y = df_comb3_no0254['cluster_3']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a logistic regression model
logreg = LogisticRegression(random_state=42)

# Train the model on the training data
logreg.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = logreg.predict(X_test)

# Evaluate the performance of the model
accuracy = logreg.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9956389651117209

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

In [71]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no0254
y = df_comb3_no0254['cluster_3']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a decision tree classifier
dt = DecisionTreeClassifier(random_state=42)

# Train the classifier on the training data
dt.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = dt.predict(X_test)

# Evaluate the performance of the model
accuracy = dt.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.999718247745982

In [72]:
from pandas._libs.tslibs import dtypes
import numpy as np
# Get the feature importances 
importances = dt.feature_importances_ 

# Get the indices that would sort the importances in ascending order
sorted_indices = np.argsort(importances)
# Print the feature importances in ascending order
for feature, importance in zip(X.columns[sorted_indices], importances[sorted_indices]):
   print(feature, importance)

LT_CAMPING_FAN_V2 0.0
JOBSSD_BLUE_COLLAR 0.0
JOBSSD_CORP_LEADER 0.0
JOBSSD_MIDDLE_MGMT 0.0
JOBSSD_RETIRED 0.0
JOBSSD_SALES 0.0
JOBSSD_STUDENT 0.0
JOB_SEEKER_ACTIVE 0.0
SD_BUSINESS_OWNER_V2 0.0
OS_LAGGARD 0.0
OS_MATERIALISM 0.0
OS_VALUE_SEEKER 0.0
APPAREL_WOMEN_PLUS_V2 0.0
HEALTH_BEAUTY 0.0
JEWELRY_PURCHASER 0.0
SD_EMPLOYMENT 0.0
JOB_SEEKER 0.0
TEAM_SPORTS_V2 0.0
SPEC_SPORT_AUTO_MC_V2 0.0
ZIPCAR_USER 0.0
BEAUTY_COSMETICS 0.0
GAMING_FANTASY_SPORTS_V2 0.0
GAMING_SPORTSBOOK_V2 0.0
HOME_DECORATING_FAN_V2 0.0
LT_FISHING_FAN_V2 0.0
LT_GAMING_FANTASY_SPORTS_V2 0.0
LT_GAMING_SPORTSBOOK_V2 0.0
LT_HOME_FURNISHINGS_DECO_V2 0.0
LT_HOME_IMPROVEMENT_V2 0.0
LT_SPEC_SPORT_AUTO_MC_V2 0.0
LT_TEAM_SPORTS_V2 0.0
OS_FOODIE 0.0
OUTDOOR_GROUPING_V2 0.0
PARENTING_CATEGORY 0.0
LT_HOME_GARDEN_V2 0.0
UBER_LYFT_USER 0.0
MAGAZINE_READER 0.0
VALUE_HUNTER 0.0
SD_GENDER:Male 0.0
SD_GENDER:Female 0.0
SD_GENDER:Inferred Female 0.0
SD_GENDER:Inferred Male 0.0
SD_GENDER:Unknown 0.0
ETHNICSD_V2:Caucasian-Other 0.0
Education:Less Than HS 0.0
ETHNICSD_V2:Hispanic 0.0
ETHNICSD_V2:Asian-Chinese 0.0
ETHNICSD_V2:Asian-Indian 0.0
ETHNICSD_V2:AA 0.0
ETHNICSD_V2:Caucasian-Jewish 0.0
ETHNICSD_V2:Middle Eastern 0.0
ETHNICSD_V2:Unknown 0.0
ETHNICSD_V2:Asian-Other 0.0
income:UNKNOWN 0.0
income:Less than $20K 0.0
income:$151K+ 0.0
HS_TRAVEL_BUSINESS 0.0
LT_TRAVEL_DOMESTIC_V2 0.0
TRAVELPROP_DOMESTIC 0.0
age:18-24 0.0
age:25-34 0.0
age:65+ 0.0
age:45-54 0.0
age:UNKNOWN 0.0
age:35-44 0.0
age:55-64 0.0
income:$61K - $80K 0.0
income:$81K - $100K 0.0
income:$21K - $40K 0.0
income:$101K - $150K 0.0
income:$41K - $60K 0.0
ONLINE_PURCHASER 0.0
SPENDEX_EDUCATION_V2 0.0
ETHNICSD_V2:Other 0.0
LT_DEAL_SITE 0.0
EXERCISE_PILATES_BARRE_V2 0.0
EXERCISE_AEROBIC_V2 0.0
SOCIALSD_INSTAGRAM_V2 0.0
REGB_FINTECH_MWALLET 0.0
REGB_FINTECH_DIGITAL 0.0
SOCIALSD_LINKEDIN_V2 0.0
REGB_CC_AIRLINE_IM 0.0
SOCIALSD_PINTEREST 0.0
SOCIALSD_SNAPCHAT 0.0
OS_FIN_PLANNING 0.0
OS_FIN_IMPCONTROL 0.0
SOCIALSD_TUMBLR 0.0
CC_USER 0.0
SOCIALSD_TWITTER 0.0
YOUNG_ADULT_IN_HH 0.0
TV_CABLE_V2 0.0
LT_DOG_OWNER_V2 0.0
TV_FAVORITES_HOME_IMP 0.0
TV_FAVORITES_NEWS 0.0
TV_STREAMING_SERV_MANY 0.0
TV_VIEWER_EMPATHIZER 0.0
CHILDREN_AGED_6_10 0.0
CHILDREN_AGED_3_5 0.0
EXERCISE_RUNNING_JOGGING_V2 0.0
EXERCISE_WALKING_V2 0.0
EXERCISE_FAN_V2 0.0
HW_DIET 0.0
AUTO_AVG_MILEAGE 0.0
INMARKET_VENMO 0.0
INMARKET_TERM_LIFE 0.0
INMARKET_ONLINEDATE 0.0
PREMOVER_V2 0.0
PREMOVER_NEW_OWNER_V2 0.0
EXERCISE_YOGA_V2 0.0
LT_EXERCISE_WALKING_V2 0.0
LT_EXERCISE_PILATES_BARRE_V2 0.0
SMARTPHONE_ANDROID_SCALE 0.0
CHILDREN_AGED_0_2 0.0
SMARTPHONE_IPHONE_SCALE 0.0
HW_YOGAPILATE 0.0
SMARTPHONE_NONE_SCALE 0.0
SOCIALSD_DEAL_SITE 0.0
HW_JOB_SATIS 0.0
HW_SLEEP_V3 0.0
HW_JUNK_DIET 0.0
LT_GOLF_FAN_V2 3.9947248371737467e-07
YOUTUBE_CREATOR 5.822488338745352e-07
SOCIALSD_FACEBOOK_V2 1.896744808095502e-06
ETHNICSD_V2:Native Amer/Pac Island 1.995120338732309e-06
CC_NEW_ISSUE 2.3842003913156936e-06
INMARKET_PAYPAL 3.611920514106089e-06
SD_LOR_V2 4.1784421595613734e-06
LT_COUPONER 5.631851457081173e-06
TV_FAVORITES_LIVE_SPORTS 6.272402719504214e-06
TRAVELPROP_INTL 6.295379156864071e-06
LT_HUNTING_SHOOTING_FAN_V2 8.279540117337936e-06
JOBSSD_HOMEMAKER 8.836094446297435e-06
LT_PET_OWNER_V2 1.2780068254786e-05
CHANNELSD_BANNER_SCALE 1.6430857268256945e-05
LT_TV_DAILY_VIEWING_V2 1.714524236687677e-05
LT_HUNTING_FAN_V2 2.5717863550315156e-05
CHANGE_IN_INCOME_12MO 2.5717863550315156e-05
OS_COOKING 2.7432387787002827e-05
LT_CAT_OWNER_V2 2.8575403944794616e-05
HW_STRESS_V2 2.8575403944794616e-05
INMARKET_ONLINEEDU_V2 3.0004174142034346e-05
LT_EXERCISE_FAN_V2 3.1432944339274076e-05
LT_SENIOR_ADULT_IN_HH_V2 3.165275513884941e-05
Education:Graduate Degree 3.184116439562829e-05
CHILDREN_AGED_16_17 3.2273397396473924e-05
AUTO_AGE 3.275710187833766e-05
LT_EXERCISE 3.366702137495801e-05
SPENDEX_PERSONAL_V2 3.428091262486232e-05
OS_INNOVATOR 3.429048473375354e-05
SPENDEX_TRAVEL_CRUISE_V2 3.6063028754703415e-05
Education:HS Degree 3.657651704933711e-05
CHILDREN_AGED_11_15 3.936828459991253e-05
OS_RISKTAKING_FIN 4.0005565522712454e-05
AUTOMOTIVE_BUFF_V2 4.572064631167138e-05
HW_SMOKING 4.572064631167139e-05
HOME_PURCHASE_PRICE 4.730030866010712e-05
Education:Bachelor Degree 5.7150807889589225e-05
CHANNELSD_INTERTV_SCALE 6.433392604775032e-05
PRESENCE_OF_CC 6.858096946750708e-05
SPENDEX_TRAVEL_INTL_V2 7.886811488763312e-05
SOCIALSD_TRIP_ADVISOR 8.229716336100849e-05
SPENDEX_TRAVEL_DOM_V2 8.397309204656785e-05
ZIP5 0.000201749860485164
SPENDEX_TRAVEL_V2 0.00022695041557597618
SPENDEX_APPAREL_V2 0.0030745216106091568
SPENDEX_PLUS_V2 0.9952458805783018

In [73]:
#confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[ 8100     9]
 [   14 73509]]

In [74]:
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split

# Load the data into a pandas dataframe

# Split the data into training and testing sets
X = features_no0254
y = df_comb3_no0254['cluster_3']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Set up the XGBoost model
params = {'objective': 'binary:logistic', 'eval_metric': 'auc'}
num_rounds = 10
early_stopping_rounds = 50
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# Train the model
modelxgb = xgb.train(params, dtrain, num_rounds, evals=[(dtest, 'test')], early_stopping_rounds=early_stopping_rounds)

# Make predictions on the test set
y_pred = model.predict(dtest)

# Calculate the accuracy score
threshold = 0.5
y_pred_binary = [1 if p > threshold else 0 for p in y_pred]
accuracy = sum(y_pred_binary == y_test) / len(y_test)
print('Accuracy: %.2f%%' % (accuracy * 100.0))

[0]	test-auc:0.99946
[1]	test-auc:0.99951
[2]	test-auc:0.99951
[3]	test-auc:0.99971
[4]	test-auc:0.99971
[5]	test-auc:0.99971
[6]	test-auc:0.99971
[7]	test-auc:0.99971
[8]	test-auc:0.99994
[9]	test-auc:0.99995
Accuracy: 9.91%

In [75]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_binary)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[ 12134      0]
 [110314      0]]