In [2]:
import pandas as pd

In [3]:
# Get in the results dataset

df_sahara2 = pd.read_csv('gs://saharadata6/consumer_behavior_consumer_clusters_all_final.csv')

In [3]:
df_sahara2

,Unnamed: 0,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,...,CHILDREN_AGED_11_17,GAMING_ESPORTS,LT_GAMING_ESPORTS,LT_HUNTING,ONLINE_PAYMENT,SOCAILMEDIA_INFLUENER,EXERCISE_INTEREST_RATING,EXERCISE,LIKELIHOODINTEREST_ONLINEPAYMENT,CLUSTER
0,0,60137,1,3,1,6,5,2,5,7,...,0,1.0,7.0,6.0,7.0,7,7,1,6.5,2
1,1,72212,1,4,0,5,2,1,5,6,...,1,0.0,4.5,4.0,5.0,7,7,1,5.0,1
2,2,60021,4,6,1,1,3,2,4,6,...,1,1.0,6.5,7.0,5.5,7,7,1,4.0,2
3,3,60085,6,1,0,2,2,6,2,1,...,0,0.0,1.0,2.0,2.5,4,7,1,2.0,4
4,4,60010,4,5,0,3,1,3,1,5,...,1,0.0,4.5,4.0,2.0,6,4,0,5.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8166064,8166064,60448,6,2,0,1,1,4,1,7,...,0,0.0,2.0,1.5,2.0,7,7,1,1.0,4
8166065,8166065,94920,7,6,1,3,3,2,1,7,...,0,0.0,3.0,4.0,4.5,7,7,1,4.5,3
8166066,8166066,60101,3,4,0,5,7,3,5,6,...,0,0.0,3.0,1.5,5.0,6,6,1,6.0,1
8166067,8166067,60466,4,5,0,6,6,2,6,6,...,0,1.0,6.5,6.5,7.0,7,7,1,7.0,2
8166068,8166068,60051,4,4,0,3,1,7,4,2,...,1,0.0,1.0,3.0,2.0,4,5,0,2.0,4

In [4]:
# Check the shape of the entire dataset (11.1M values to 8.17M after dropping duplicates)
df_sahara2 = df_sahara2.drop_duplicates()
df_sahara2.shape

(8166069, 119)

In [4]:
# Check all features which are strings

dtypes = df_sahara2.dtypes

string_cols = [col for col, dtype in dtypes.items() if dtype == 'object']
string_cols

[]

In [5]:
# Create dummies for Clusters

# Get the unique values in the 'Cluster' column
clusters = df_sahara2['CLUSTER'].unique()

# Create a loop to create dummy variables for each unique value
for cluster in clusters:
    column_name = f"cluster_{cluster}"
    df_sahara2[column_name] = (df_sahara2['CLUSTER'] == cluster).astype(int)

# Print the updated DataFrame to verify if the new columns have been added
df_sahara2.head()

,Unnamed: 0,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,...,SOCAILMEDIA_INFLUENER,EXERCISE_INTEREST_RATING,EXERCISE,LIKELIHOODINTEREST_ONLINEPAYMENT,CLUSTER,cluster_2,cluster_1,cluster_4,cluster_0,cluster_3
0,0,60137,1,3,1,6,5,2,5,7,...,7,7,1,6.5,2,1,0,0,0,0
1,1,72212,1,4,0,5,2,1,5,6,...,7,7,1,5.0,1,0,1,0,0,0
2,2,60021,4,6,1,1,3,2,4,6,...,7,7,1,4.0,2,1,0,0,0,0
3,3,60085,6,1,0,2,2,6,2,1,...,4,7,1,2.0,4,0,0,1,0,0
4,4,60010,4,5,0,3,1,3,1,5,...,6,4,0,5.0,0,0,0,0,1,0

In [6]:
# Delete Cluster and Unnamed

cols_to_drop = ['CLUSTER', 'Unnamed: 0']
df_sahara2 = df_sahara2.drop(columns=cols_to_drop)

In [9]:
df_sahara2

,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,SMARTPHONE_NONE_SCALE,...,ONLINE_PAYMENT,SOCAILMEDIA_INFLUENER,EXERCISE_INTEREST_RATING,EXERCISE,LIKELIHOODINTEREST_ONLINEPAYMENT,cluster_2,cluster_1,cluster_4,cluster_0,cluster_3
0,60137,1,3,1,6,5,2,5,7,2,...,7.0,7,7,1,6.5,1,0,0,0,0
1,72212,1,4,0,5,2,1,5,6,2,...,5.0,7,7,1,5.0,0,1,0,0,0
2,60021,4,6,1,1,3,2,4,6,2,...,5.5,7,7,1,4.0,1,0,0,0,0
3,60085,6,1,0,2,2,6,2,1,7,...,2.5,4,7,1,2.0,0,0,1,0,0
4,60010,4,5,0,3,1,3,1,5,6,...,2.0,6,4,0,5.0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8166064,60448,6,2,0,1,1,4,1,7,2,...,2.0,7,7,1,1.0,0,0,1,0,0
8166065,94920,7,6,1,3,3,2,1,7,3,...,4.5,7,7,1,4.5,0,0,0,0,1
8166066,60101,3,4,0,5,7,3,5,6,2,...,5.0,6,6,1,6.0,0,1,0,0,0
8166067,60466,4,5,0,6,6,2,6,6,2,...,7.0,7,7,1,7.0,1,0,0,0,0
8166068,60051,4,4,0,3,1,7,4,2,6,...,2.0,4,5,0,2.0,0,0,1,0,0

In [10]:
# Create a DataFrame with only Features
features = df_sahara2.drop(['cluster_0', 'cluster_1', 'cluster_2', 'cluster_3', 'cluster_4'], axis = 1)

In [11]:
# Model building

## CLUSTER 0
# Logistic Regression

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features
y = df_sahara2['cluster_0']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a logistic regression model
logreg = LogisticRegression(random_state=42)

# Train the model on the training data
logreg.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = logreg.predict(X_test)

# Evaluate the performance of the model
accuracy = logreg.score(X_test, y_test)
print("Accuracy:", accuracy)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

Accuracy: 0.8014246755171092

In [12]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[1291893   15295]
 [ 309021   17005]]

In [13]:
## Decision Tree Modeling

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features
y = df_sahara2['cluster_0']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a decision tree classifier
dt = DecisionTreeClassifier(random_state=42)

# Train the classifier on the training data
dt.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = dt.predict(X_test)

# Evaluate the performance of the model
accuracy = dt.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.978449241801748

In [14]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[1289638   17550]
 [  17647  308379]]

In [17]:
# Important Features
from pandas._libs.tslibs import dtypes
import numpy as np

# Get the feature importances 
importances = dt.feature_importances_ 

# Get the indices that would sort the importances in ascending order
sorted_indices = np.argsort(importances)
# Print the feature importances in ascending order
for feature, importance in zip(X.columns[sorted_indices], importances[sorted_indices]):
   print(feature, importance)

PREMOVER_NEW_OWNER_V2 0.0
APPAREL_WOMEN_PLUS_V2 1.4983486960063845e-06
JOB_SEEKER_ACTIVE 6.551980010484763e-05
PARENTING_CATEGORY 9.88009561382414e-05
HOME_DECORATING_FAN_V2 0.00011655510825113214
TV_CABLE_V2 0.0001234419618223485
TEAM_SPORTS_V2 0.0001237043141189234
SPEC_SPORT_AUTO_MC_V2 0.0001253568882537567
CC_NEW_ISSUE 0.00012749886310699105
ONLINE_PURCHASER 0.00012882182065711344
JEWELRY_PURCHASER 0.0001301663151855936
YOUNG_ADULT_IN_HH 0.0001307190307500906
CHILDREN_AGED_11_17 0.00013975431442912663
AUTOMOTIVE_BUFF_V2 0.0001478697767353288
CHILDREN_AGED_0_10 0.00015346246741653716
MAGAZINE_READER 0.00016013171448861526
VALUE_HUNTER 0.00017352656517610708
JOB_SEEKER 0.0002653308486746465
PRESENCE_OF_CC 0.00027302959917900144
HS_TRAVEL_BUSINESS 0.0002878043524111247
BEAUTY_COSMETICS 0.0002933603328746192
CC_USER 0.0002977443925515681
SD_HOMEOWNER_PROB_V2 0.00032366710435830946
AGE_GROUP 0.00032366993737230245
CHANGE_IN_INCOME_12MO 0.0003445359666758378
PRESENCE_OF_CHILDREN 0.0003511707621128863
SD_CHILDREN_IN_HH 0.0003685588099252168
HEALTH_BEAUTY 0.0003688797428441758
JOBSSD_STUDENT 0.0003752250683790024
SD_EDUCATION_V2 0.00040543051149060364
JOBSSD_SALES 0.00048754031621902396
SD_ADULTS_IN_HH 0.0004933759071916482
OS_FIN_PLANNING 0.0005036622104308922
LT_TRAVEL_DOMESTIC_V2 0.0005119008557428865
JOBSSD_HOMEMAKER 0.0005147120326779916
ETHNICSD_V2 0.0005316921507265321
SD_PEOPLE_IN_HH 0.0005422349722260794
REGB_CC_AIRLINE_IM 0.0005529255505918678
JOBSSD_MIDDLE_MGMT 0.0005938742659622142
LT_HOME_IMPROVEMENT_V2 0.0006085269336231666
TV_FAVORITES_HOME_IMP 0.0006148109874762115
INMARKET_TERM_LIFE 0.0006237989177004256
OS_VALUE_SEEKER 0.0006298643344137136
LT_HOME_GARDEN_V2 0.0006414245509369586
OS_RISKTAKING_FIN 0.000657729458145366
LT_SPEC_SPORT_AUTO_MC_V2 0.0006734380039421606
GAMING_ESPORTS 0.0006923545196256818
AUTO_AVG_MILEAGE 0.0006953482969281504
LT_FISHING_FAN_V2 0.000706302640368144
INMARKET_ONLINEDATE 0.0007201444167322539
TV_FAVORITES_LIVE_SPORTS 0.0007204993828827779
PREMOVER_V2 0.0007353030808854449
HW_SMOKING 0.0007420925528874393
JOBSSD_BLUE_COLLAR 0.0007482783785780808
LT_TEAM_SPORTS_V2 0.0007583158555287283
HW_JUNK_DIET 0.0007675163387526776
LT_PET_OWNER_V2 0.0007849066451772705
AUTO_AGE 0.0008009413380856202
CHANNELSD_BANNER_SCALE 0.0008154079316579824
REGB_FINTECH_DIGITAL 0.0008355064437877061
LT_COUPONER 0.0008388707863007074
JOBSSD_CORP_LEADER 0.0009163131198918589
LT_CAMPING_FAN_V2 0.0009187483086298592
LT_SENIOR_ADULT_IN_HH_V2 0.0009188323056617333
OUTDOOR_GROUPING_V2 0.0009660626768066034
INCOME_GROUP 0.0009888817364091277
LT_GAMING_ESPORTS 0.0009966973407217264
LT_HUNTING 0.0010130689692577806
OS_COOKING 0.0010401617524656715
LT_EXERCISE 0.0010587975044128247
LT_GOLF_FAN_V2 0.0010621828481293377
REGB_FINTECH_MWALLET 0.0010788861410164095
UBER_LYFT_USER 0.0011130137617309157
EXERCISE 0.0011463179707964304
SD_BUSINESS_OWNER_V2 0.0011867160076802898
JOBSSD_RETIRED 0.0011951186748910768
ZIPCAR_USER 0.001232747479705218
HOME_PURCHASE_PRICE 0.001274715032280166
CHANNELSD_INTERTV_SCALE 0.0013020122569814517
SMARTPHONE_IPHONE_SCALE 0.0013266810663054157
SPENDEX_APPAREL_V2 0.001365103064481764
SMARTPHONE_ANDROID_SCALE 0.0014477973751708332
HW_JOB_SATIS 0.0014878312257673384
SD_HOME_AGE 0.0015682705501605062
SPENDEX_PERSONAL_V2 0.0016225051293596606
OS_INNOVATOR 0.0016332108169093932
SPENDEX_TRAVEL_V2 0.0016471247777097614
OS_FIN_IMPCONTROL 0.001675103959430243
SOCIALSD_DEAL_SITE 0.0019589499815598124
EXERCISE_INTEREST_RATING 0.0021020691619906976
SPENDEX_PLUS_V2 0.00214141653199221
HW_DIET 0.0022546175603683034
HW_STRESS_V2 0.002262544639615944
LT_TV_DAILY_VIEWING_V2 0.0022874008991724325
SD_LOR_V2 0.00229421048010185
SMARTPHONE_NONE_SCALE 0.0024637139626287876
LT_DEAL_SITE 0.0028771604104700648
OS_LAGGARD 0.0029465766514694615
TV_FAVORITES_NEWS 0.0029853462672951403
ZIP5 0.0029908376657202477
TRAVELPROP 0.002998198120447973
LIKELIHOODINTEREST_ONLINEPAYMENT 0.0030641962453574734
OS_FOODIE 0.0035242271004055177
TV_STREAMING_SERV_MANY 0.003939906027336433
CHANGE_IN_HOME_VALUE_12MO 0.004203822985945441
HW_SLEEP_V3 0.005063819793702348
SOCIALSD_TRIP_ADVISOR 0.005245560225387223
INMARKET_ONLINEEDU_V2 0.006303045414495256
OS_MATERIALISM 0.010035129258186242
SOCIALSD_TUMBLR 0.0171223347001622
SOCAILMEDIA_INFLUENER 0.019293315457973463
SPENDEX_EDUCATION_V2 0.03538547196788969
ONLINE_PAYMENT 0.060974923235320486
SD_GENDER 0.1326275121488507
LT_HOME_FURNISHINGS_DECO_V2 0.1370292516501542
SD_EMPLOYMENT 0.18852526459348853
TV_VIEWER_EMPATHIZER 0.2751477392793827

In [ ]:
# GAP

In [15]:
## CLUSTER 2

# Preparing file for cluster_2 prediction

# First make predictions using the decision tree
predictions0 = dt.predict(features) 
df_sahara2['predictions0'] = predictions0 
df_sahara2

,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,SMARTPHONE_NONE_SCALE,...,SOCAILMEDIA_INFLUENER,EXERCISE_INTEREST_RATING,EXERCISE,LIKELIHOODINTEREST_ONLINEPAYMENT,cluster_2,cluster_1,cluster_4,cluster_0,cluster_3,predictions0
0,60137,1,3,1,6,5,2,5,7,2,...,7,7,1,6.5,1,0,0,0,0,0
1,72212,1,4,0,5,2,1,5,6,2,...,7,7,1,5.0,0,1,0,0,0,0
2,60021,4,6,1,1,3,2,4,6,2,...,7,7,1,4.0,1,0,0,0,0,0
3,60085,6,1,0,2,2,6,2,1,7,...,4,7,1,2.0,0,0,1,0,0,0
4,60010,4,5,0,3,1,3,1,5,6,...,6,4,0,5.0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8166064,60448,6,2,0,1,1,4,1,7,2,...,7,7,1,1.0,0,0,1,0,0,0
8166065,94920,7,6,1,3,3,2,1,7,3,...,7,7,1,4.5,0,0,0,0,1,0
8166066,60101,3,4,0,5,7,3,5,6,2,...,6,6,1,6.0,0,1,0,0,0,0
8166067,60466,4,5,0,6,6,2,6,6,2,...,7,7,1,7.0,1,0,0,0,0,0
8166068,60051,4,4,0,3,1,7,4,2,6,...,4,5,0,2.0,0,0,1,0,0,0

In [16]:
# Drop columns 
df_sahara2_no0 = df_sahara2[df_sahara2["predictions0"] < 0.5].drop("predictions0", axis=1)

In [20]:
df_sahara2_no0

,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,SMARTPHONE_NONE_SCALE,...,ONLINE_PAYMENT,SOCAILMEDIA_INFLUENER,EXERCISE_INTEREST_RATING,EXERCISE,LIKELIHOODINTEREST_ONLINEPAYMENT,cluster_2,cluster_1,cluster_4,cluster_0,cluster_3
0,60137,1,3,1,6,5,2,5,7,2,...,7.0,7,7,1,6.5,1,0,0,0,0
1,72212,1,4,0,5,2,1,5,6,2,...,5.0,7,7,1,5.0,0,1,0,0,0
2,60021,4,6,1,1,3,2,4,6,2,...,5.5,7,7,1,4.0,1,0,0,0,0
3,60085,6,1,0,2,2,6,2,1,7,...,2.5,4,7,1,2.0,0,0,1,0,0
5,60629,4,1,0,6,7,3,6,6,2,...,5.5,6,7,1,5.5,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8166064,60448,6,2,0,1,1,4,1,7,2,...,2.0,7,7,1,1.0,0,0,1,0,0
8166065,94920,7,6,1,3,3,2,1,7,3,...,4.5,7,7,1,4.5,0,0,0,0,1
8166066,60101,3,4,0,5,7,3,5,6,2,...,5.0,6,6,1,6.0,0,1,0,0,0
8166067,60466,4,5,0,6,6,2,6,6,2,...,7.0,7,7,1,7.0,1,0,0,0,0
8166068,60051,4,4,0,3,1,7,4,2,6,...,2.0,4,5,0,2.0,0,0,1,0,0

In [17]:
# Model building for cluster_2

# Create a dataframe with just the features without cluster 0 
features_no0 = df_sahara2_no0.drop(['cluster_0', 'cluster_1', 'cluster_2', 'cluster_3', 'cluster_4'], axis = 1)
features_no0

,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,SMARTPHONE_NONE_SCALE,...,CHILDREN_AGED_0_10,CHILDREN_AGED_11_17,GAMING_ESPORTS,LT_GAMING_ESPORTS,LT_HUNTING,ONLINE_PAYMENT,SOCAILMEDIA_INFLUENER,EXERCISE_INTEREST_RATING,EXERCISE,LIKELIHOODINTEREST_ONLINEPAYMENT
0,60137,1,3,1,6,5,2,5,7,2,...,0,0,1.0,7.0,6.0,7.0,7,7,1,6.5
1,72212,1,4,0,5,2,1,5,6,2,...,1,1,0.0,4.5,4.0,5.0,7,7,1,5.0
2,60021,4,6,1,1,3,2,4,6,2,...,1,1,1.0,6.5,7.0,5.5,7,7,1,4.0
3,60085,6,1,0,2,2,6,2,1,7,...,0,0,0.0,1.0,2.0,2.5,4,7,1,2.0
5,60629,4,1,0,6,7,3,6,6,2,...,1,1,0.0,4.5,2.5,5.5,6,7,1,5.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8166064,60448,6,2,0,1,1,4,1,7,2,...,0,0,0.0,2.0,1.5,2.0,7,7,1,1.0
8166065,94920,7,6,1,3,3,2,1,7,3,...,0,0,0.0,3.0,4.0,4.5,7,7,1,4.5
8166066,60101,3,4,0,5,7,3,5,6,2,...,0,0,0.0,3.0,1.5,5.0,6,6,1,6.0
8166067,60466,4,5,0,6,6,2,6,6,2,...,0,0,1.0,6.5,6.5,7.0,7,7,1,7.0
8166068,60051,4,4,0,3,1,7,4,2,6,...,1,1,0.0,1.0,3.0,2.0,4,5,0,2.0

In [22]:
## Logisitc Regression

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no0
y = df_sahara2_no0['cluster_2']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a logistic regression model
logreg = LogisticRegression(random_state=42)

# Train the model on the training data
logreg.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = logreg.predict(X_test)

# Evaluate the performance of the model
accuracy = logreg.score(X_test, y_test)
print("Accuracy:", accuracy)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

Accuracy: 0.7561557046240728

In [23]:
# Confusion matrix for cluster 2

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[933946  25499]
 [293334  54748]]

In [18]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no0
y = df_sahara2_no0['cluster_2']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a decision tree classifier
dt = DecisionTreeClassifier(random_state=42)

# Train the classifier on the training data
dt.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = dt.predict(X_test)

# Evaluate the performance of the model
accuracy = dt.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9739171734120978

In [19]:
# Confusion matrix Decision Tree
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[942252  17193]
 [ 16911 331171]]

In [27]:
# Important Features
from pandas._libs.tslibs import dtypes
import numpy as np
# Get the feature importances 
importances = dt.feature_importances_ 

# Get the indices that would sort the importances in ascending order
sorted_indices = np.argsort(importances)
# Print the feature importances in ascending order
for feature, importance in zip(X.columns[sorted_indices], importances[sorted_indices]):
   print(feature, importance)

APPAREL_WOMEN_PLUS_V2 0.0
PREMOVER_NEW_OWNER_V2 2.472529503546323e-06
YOUNG_ADULT_IN_HH 8.304192385515708e-05
CC_NEW_ISSUE 8.913569430413696e-05
VALUE_HUNTER 9.849245664008807e-05
PARENTING_CATEGORY 0.00011235097353434612
JEWELRY_PURCHASER 0.00011678734972700191
EXERCISE 0.00011912830240233733
HOME_DECORATING_FAN_V2 0.00012160811601123217
BEAUTY_COSMETICS 0.0001428921434293056
HEALTH_BEAUTY 0.00014470698926143593
MAGAZINE_READER 0.0001642963526015373
ONLINE_PURCHASER 0.0001729058696650139
LT_DEAL_SITE 0.0001825818837149178
TV_CABLE_V2 0.00019682435068995948
CHILDREN_AGED_0_10 0.00020821409851827364
CHILDREN_AGED_11_17 0.00022953412925237816
SOCAILMEDIA_INFLUENER 0.00027249203007753404
CHANGE_IN_INCOME_12MO 0.00032991924631315154
PRESENCE_OF_CC 0.0004010040123817122
SMARTPHONE_IPHONE_SCALE 0.00040230839094956155
JOBSSD_STUDENT 0.0004248558697981257
JOBSSD_RETIRED 0.000425989641547409
HS_TRAVEL_BUSINESS 0.0004266212410236279
JOBSSD_BLUE_COLLAR 0.0004459865557736503
SD_HOMEOWNER_PROB_V2 0.0004993285286780986
HW_DIET 0.0005004117837817864
SD_ADULTS_IN_HH 0.0005151191458354052
JOBSSD_SALES 0.0005364341712899643
EXERCISE_INTEREST_RATING 0.0005387294956611414
LT_EXERCISE 0.0005737992917645033
OS_FOODIE 0.0005879152033002287
JOBSSD_MIDDLE_MGMT 0.00059168161320926
INMARKET_ONLINEEDU_V2 0.0005983050077044263
REGB_FINTECH_DIGITAL 0.0006083231180219854
SD_EDUCATION_V2 0.0006095558359943771
PRESENCE_OF_CHILDREN 0.0006101198863436529
LT_HOME_GARDEN_V2 0.000643846848296922
LT_HOME_IMPROVEMENT_V2 0.0006634484325969186
LT_TV_DAILY_VIEWING_V2 0.0006796829964324154
AUTO_AVG_MILEAGE 0.0006869779773085727
TV_FAVORITES_HOME_IMP 0.0006945294314757478
AUTOMOTIVE_BUFF_V2 0.0007141577455485914
SOCIALSD_DEAL_SITE 0.0007181032232738398
LT_HOME_FURNISHINGS_DECO_V2 0.0007210345336967325
REGB_FINTECH_MWALLET 0.0007246886043937017
ETHNICSD_V2 0.0007288184024015721
TV_VIEWER_EMPATHIZER 0.000730793367332963
CHANNELSD_INTERTV_SCALE 0.0007383887423103522
PREMOVER_V2 0.0007417641295550735
HW_JOB_SATIS 0.0007492652981661229
UBER_LYFT_USER 0.0007720846217958152
OS_MATERIALISM 0.0007722211246276658
SD_BUSINESS_OWNER_V2 0.0007945386613284975
LT_SENIOR_ADULT_IN_HH_V2 0.0008136869193109304
LT_COUPONER 0.0008237443921688812
LT_PET_OWNER_V2 0.0008479767565234767
SD_CHILDREN_IN_HH 0.000880664331410322
OS_COOKING 0.0008999428679449743
OUTDOOR_GROUPING_V2 0.0009109251029832062
SD_PEOPLE_IN_HH 0.0009401427629200709
JOBSSD_HOMEMAKER 0.0009415893002760057
LT_TRAVEL_DOMESTIC_V2 0.0009631982693959797
SPENDEX_PLUS_V2 0.0009985776299999765
SPENDEX_APPAREL_V2 0.0010075303461435537
SMARTPHONE_NONE_SCALE 0.0010203146691762143
TV_FAVORITES_LIVE_SPORTS 0.0010299121032917359
JOBSSD_CORP_LEADER 0.001032501718917383
SOCIALSD_TRIP_ADVISOR 0.001074068438250468
LIKELIHOODINTEREST_ONLINEPAYMENT 0.0010917035391371352
INMARKET_TERM_LIFE 0.0011166679513417497
SD_EMPLOYMENT 0.001123741874138036
CHANNELSD_BANNER_SCALE 0.0011357274129453606
LT_FISHING_FAN_V2 0.001140241180997766
OS_RISKTAKING_FIN 0.0011639203445644685
SMARTPHONE_ANDROID_SCALE 0.0013466980382287887
SPENDEX_PERSONAL_V2 0.0014012900795126485
OS_INNOVATOR 0.001469997664420764
AUTO_AGE 0.0014748381540443584
AGE_GROUP 0.0014793187439688953
LT_SPEC_SPORT_AUTO_MC_V2 0.0015476024413217824
SD_LOR_V2 0.0015502835739657794
CC_USER 0.0015595409963446109
LT_TEAM_SPORTS_V2 0.0015603591197591847
HOME_PURCHASE_PRICE 0.0015933357089077007
JOB_SEEKER_ACTIVE 0.0016312417917756779
OS_VALUE_SEEKER 0.0016525024650705098
HW_SLEEP_V3 0.0017092805131273604
SD_HOME_AGE 0.0018072253236042566
LT_HUNTING 0.0018151086926771697
OS_FIN_IMPCONTROL 0.0019418187921904117
SD_GENDER 0.0019494472055208815
LT_GOLF_FAN_V2 0.001961280161043541
JOB_SEEKER 0.0020191035007648688
ONLINE_PAYMENT 0.0020769267439041247
ZIP5 0.002109337570815967
HW_STRESS_V2 0.00211286478484632
TEAM_SPORTS_V2 0.0021791542281485877
HW_SMOKING 0.0022510637178405385
SOCIALSD_TUMBLR 0.0022689502339874393
REGB_CC_AIRLINE_IM 0.002501157513460844
OS_FIN_PLANNING 0.002513014527636682
INMARKET_ONLINEDATE 0.0027592867047022676
GAMING_ESPORTS 0.0032778089176562558
HW_JUNK_DIET 0.0036787202624069567
SPENDEX_EDUCATION_V2 0.003912878381922398
ZIPCAR_USER 0.005254743232021077
INCOME_GROUP 0.006033866605272507
TRAVELPROP 0.0067344527201676375
SPEC_SPORT_AUTO_MC_V2 0.007392608122785989
TV_STREAMING_SERV_MANY 0.008440768250415148
CHANGE_IN_HOME_VALUE_12MO 0.009823934097626134
LT_CAMPING_FAN_V2 0.011075107345022954
OS_LAGGARD 0.026610306530199048
TV_FAVORITES_NEWS 0.04542083317997511
SPENDEX_TRAVEL_V2 0.08998208633475528
LT_GAMING_ESPORTS 0.6748048617432418

In [28]:
pip install xgboost

Requirement already satisfied: xgboost in /opt/conda/lib/python3.7/site-packages (1.6.2)
Requirement already satisfied: numpy in /opt/conda/lib/python3.7/site-packages (from xgboost) (1.21.6)
Requirement already satisfied: scipy in /opt/conda/lib/python3.7/site-packages (from xgboost) (1.7.3)
Note: you may need to restart the kernel to use updated packages.

In [38]:
import xgboost as xgb

In [30]:
# Gradient Boost

import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split

# Load the data into a pandas dataframe

# Split the data into training and testing sets
X = features_no0
y = df_sahara2_no0['cluster_2']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Set up the XGBoost model
params = {'objective': 'binary:logistic', 'eval_metric': 'auc'}
num_rounds = 10
early_stopping_rounds = 50
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# Train the model
model = xgb.train(params, dtrain, num_rounds, evals=[(dtest, 'test')], early_stopping_rounds=early_stopping_rounds)

# Make predictions on the test set
y_pred = model.predict(dtest)

# Calculate the accuracy score
threshold = 0.5
y_pred_binary = [1 if p > threshold else 0 for p in y_pred]
accuracy = sum(y_pred_binary == y_test) / len(y_test)
print('Accuracy: %.2f%%' % (accuracy * 100.0))

[0]	test-auc:0.99259
[1]	test-auc:0.99491
[2]	test-auc:0.99574
[3]	test-auc:0.99640
[4]	test-auc:0.99668
[5]	test-auc:0.99700
[6]	test-auc:0.99725
[7]	test-auc:0.99743
[8]	test-auc:0.99760
[9]	test-auc:0.99780
Accuracy: 97.81%

In [ ]:
# GAP

In [20]:
## CLUSTER 1

# Preparing file for cluster_5 prediction

# First make predictions using the decision tree for Cluster 2
predictions2 = dt.predict(features_no0) 
df_sahara2_no0['predictions2'] = predictions2
df_sahara2_no0

,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,SMARTPHONE_NONE_SCALE,...,SOCAILMEDIA_INFLUENER,EXERCISE_INTEREST_RATING,EXERCISE,LIKELIHOODINTEREST_ONLINEPAYMENT,cluster_2,cluster_1,cluster_4,cluster_0,cluster_3,predictions2
0,60137,1,3,1,6,5,2,5,7,2,...,7,7,1,6.5,1,0,0,0,0,1
1,72212,1,4,0,5,2,1,5,6,2,...,7,7,1,5.0,0,1,0,0,0,0
2,60021,4,6,1,1,3,2,4,6,2,...,7,7,1,4.0,1,0,0,0,0,1
3,60085,6,1,0,2,2,6,2,1,7,...,4,7,1,2.0,0,0,1,0,0,0
5,60629,4,1,0,6,7,3,6,6,2,...,6,7,1,5.5,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8166064,60448,6,2,0,1,1,4,1,7,2,...,7,7,1,1.0,0,0,1,0,0,0
8166065,94920,7,6,1,3,3,2,1,7,3,...,7,7,1,4.5,0,0,0,0,1,0
8166066,60101,3,4,0,5,7,3,5,6,2,...,6,6,1,6.0,0,1,0,0,0,0
8166067,60466,4,5,0,6,6,2,6,6,2,...,7,7,1,7.0,1,0,0,0,0,1
8166068,60051,4,4,0,3,1,7,4,2,6,...,4,5,0,2.0,0,0,1,0,0,0

In [21]:
# Drop columns 
df_sahara2_no02 = df_sahara2_no0[df_sahara2_no0["predictions2"] < 0.5].drop("predictions2", axis=1)

In [22]:
# Quick check
df_sahara2_no02

,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,SMARTPHONE_NONE_SCALE,...,ONLINE_PAYMENT,SOCAILMEDIA_INFLUENER,EXERCISE_INTEREST_RATING,EXERCISE,LIKELIHOODINTEREST_ONLINEPAYMENT,cluster_2,cluster_1,cluster_4,cluster_0,cluster_3
1,72212,1,4,0,5,2,1,5,6,2,...,5.0,7,7,1,5.0,0,1,0,0,0
3,60085,6,1,0,2,2,6,2,1,7,...,2.5,4,7,1,2.0,0,0,1,0,0
5,60629,4,1,0,6,7,3,6,6,2,...,5.5,6,7,1,5.5,0,1,0,0,0
8,60020,7,5,0,6,4,4,3,3,6,...,4.5,5,6,0,2.5,0,1,0,0,0
9,95409,6,2,0,4,1,6,4,5,6,...,2.0,7,6,1,4.0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8166062,95118,6,4,0,7,7,2,4,7,3,...,4.5,7,7,1,5.0,0,0,0,0,1
8166064,60448,6,2,0,1,1,4,1,7,2,...,2.0,7,7,1,1.0,0,0,1,0,0
8166065,94920,7,6,1,3,3,2,1,7,3,...,4.5,7,7,1,4.5,0,0,0,0,1
8166066,60101,3,4,0,5,7,3,5,6,2,...,5.0,6,6,1,6.0,0,1,0,0,0
8166068,60051,4,4,0,3,1,7,4,2,6,...,2.0,4,5,0,2.0,0,0,1,0,0

In [23]:
# Model building for cluster_1

# Create a dataframe with just the features without cluster 0 
features_no02 = df_sahara2_no02.drop(['cluster_0', 'cluster_1', 'cluster_2', 'cluster_3', 'cluster_4'], axis = 1)
features_no02

,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,SMARTPHONE_NONE_SCALE,...,CHILDREN_AGED_0_10,CHILDREN_AGED_11_17,GAMING_ESPORTS,LT_GAMING_ESPORTS,LT_HUNTING,ONLINE_PAYMENT,SOCAILMEDIA_INFLUENER,EXERCISE_INTEREST_RATING,EXERCISE,LIKELIHOODINTEREST_ONLINEPAYMENT
1,72212,1,4,0,5,2,1,5,6,2,...,1,1,0.0,4.5,4.0,5.0,7,7,1,5.0
3,60085,6,1,0,2,2,6,2,1,7,...,0,0,0.0,1.0,2.0,2.5,4,7,1,2.0
5,60629,4,1,0,6,7,3,6,6,2,...,1,1,0.0,4.5,2.5,5.5,6,7,1,5.5
8,60020,7,5,0,6,4,4,3,3,6,...,1,1,0.0,3.0,5.5,4.5,5,6,0,2.5
9,95409,6,2,0,4,1,6,4,5,6,...,0,0,0.0,1.5,2.0,2.0,7,6,1,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8166062,95118,6,4,0,7,7,2,4,7,3,...,1,1,0.0,4.0,1.0,4.5,7,7,1,5.0
8166064,60448,6,2,0,1,1,4,1,7,2,...,0,0,0.0,2.0,1.5,2.0,7,7,1,1.0
8166065,94920,7,6,1,3,3,2,1,7,3,...,0,0,0.0,3.0,4.0,4.5,7,7,1,4.5
8166066,60101,3,4,0,5,7,3,5,6,2,...,0,0,0.0,3.0,1.5,5.0,6,6,1,6.0
8166068,60051,4,4,0,3,1,7,4,2,6,...,1,1,0.0,1.0,3.0,2.0,4,5,0,2.0

In [24]:
# Let's start with Logistic again
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no02
y = df_sahara2_no02['cluster_1']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a logistic regression model
logreg = LogisticRegression(random_state=42)

# Train the model on the training data
logreg.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = logreg.predict(X_test)

# Evaluate the performance of the model
accuracy = logreg.score(X_test, y_test)
print("Accuracy:", accuracy)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

Accuracy: 0.825467793026219

In [25]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[552855  74113]
 [ 93277 238833]]

In [37]:
# Random Forest (Cluster 1)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no02
y = df_sahara2_no02['cluster_1']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a random forest classifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the classifier on the training data
rf.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = rf.predict(X_test)

# Evaluate the performance of the model
accuracy = rf.score(X_test, y_test)
print("Accuracy:", accuracy)

KeyboardInterrupt:

In [ ]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

In [26]:
# Decision Tree

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no02
y = df_sahara2_no02['cluster_1']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a decision tree classifier
dt = DecisionTreeClassifier(random_state=42)

# Train the classifier on the training data
dt.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = dt.predict(X_test)

# Evaluate the performance of the model
accuracy = dt.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9526951926746312

In [27]:
#confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[604412  22556]
 [ 22813 309297]]

In [41]:
from pandas._libs.tslibs import dtypes
import numpy as np
# Get the feature importances 
importances = dt.feature_importances_ 

# Get the indices that would sort the importances in ascending order
sorted_indices = np.argsort(importances)
# Print the feature importances in ascending order
for feature, importance in zip(X.columns[sorted_indices], importances[sorted_indices]):
   print(feature, importance)

PREMOVER_NEW_OWNER_V2 2.7656352546913373e-06
TEAM_SPORTS_V2 7.158002529952726e-05
APPAREL_WOMEN_PLUS_V2 9.128023687586454e-05
SPEC_SPORT_AUTO_MC_V2 0.00014299326294229378
GAMING_ESPORTS 0.00015819624673889563
VALUE_HUNTER 0.00016586389202113185
YOUNG_ADULT_IN_HH 0.0001807491902814034
CC_NEW_ISSUE 0.00018955401185897648
PARENTING_CATEGORY 0.00019434137693410164
JEWELRY_PURCHASER 0.0002051448445666161
JOB_SEEKER_ACTIVE 0.00021990878812542717
HOME_DECORATING_FAN_V2 0.00025597234690282584
AUTOMOTIVE_BUFF_V2 0.00025680500096187384
ONLINE_PURCHASER 0.0002714286118318819
EXERCISE 0.0003126984048645804
MAGAZINE_READER 0.0003136689771459736
CHILDREN_AGED_11_17 0.00037426075743123883
CHANGE_IN_INCOME_12MO 0.00039823050170463575
CHILDREN_AGED_0_10 0.00042996857650256766
TV_CABLE_V2 0.00043903328506436927
PRESENCE_OF_CHILDREN 0.0005155033823779114
BEAUTY_COSMETICS 0.0005231426038099549
HS_TRAVEL_BUSINESS 0.0005996661324652557
LT_HOME_FURNISHINGS_DECO_V2 0.0006568711031784226
HW_DIET 0.0006928301842890892
JOBSSD_BLUE_COLLAR 0.0007146182265871282
SD_ADULTS_IN_HH 0.000717178153521408
JOBSSD_STUDENT 0.0007282800371340975
LT_FISHING_FAN_V2 0.0007540472508613683
EXERCISE_INTEREST_RATING 0.0007714104114400648
JOBSSD_MIDDLE_MGMT 0.000775998579287019
CC_USER 0.0007826041743748875
JOBSSD_HOMEMAKER 0.0008046195041245084
OUTDOOR_GROUPING_V2 0.0008061295555257219
JOBSSD_SALES 0.0008278145012695955
SMARTPHONE_IPHONE_SCALE 0.0008435547325902328
JOB_SEEKER 0.000844959942036816
LT_HOME_IMPROVEMENT_V2 0.0008507565109542893
LT_EXERCISE 0.000855670791503462
LT_DEAL_SITE 0.0008776005558141978
ETHNICSD_V2 0.0008779571979520346
SD_CHILDREN_IN_HH 0.0008882254336726549
TV_FAVORITES_HOME_IMP 0.0008919169735905491
SD_PEOPLE_IN_HH 0.0009086557763799763
LT_SPEC_SPORT_AUTO_MC_V2 0.0009176234241773504
HW_JUNK_DIET 0.0009224886858520087
LT_HOME_GARDEN_V2 0.0009230669409001288
LT_CAMPING_FAN_V2 0.0009253548989084865
OS_RISKTAKING_FIN 0.0009376948057605397
REGB_FINTECH_DIGITAL 0.0009617700390812788
SD_EDUCATION_V2 0.0009846005902401315
AGE_GROUP 0.0010234600584644261
OS_VALUE_SEEKER 0.0011382718482295315
HEALTH_BEAUTY 0.0011483045968235426
LT_TEAM_SPORTS_V2 0.001174583201322072
LT_HUNTING 0.001182975034030053
JOBSSD_RETIRED 0.001190123168973361
AUTO_AVG_MILEAGE 0.0012068743133860588
SD_HOMEOWNER_PROB_V2 0.0012316549424179468
OS_INNOVATOR 0.0012922437944683555
LT_SENIOR_ADULT_IN_HH_V2 0.0013015583426245188
REGB_FINTECH_MWALLET 0.0013016125765238317
SOCAILMEDIA_INFLUENER 0.001335722501805736
LT_COUPONER 0.0013769268568197808
SOCIALSD_TRIP_ADVISOR 0.001396065016059843
OS_FOODIE 0.0014572859916873594
SD_EMPLOYMENT 0.0015068696048044258
SPENDEX_APPAREL_V2 0.0015486851632544674
PREMOVER_V2 0.0016122366094260703
PRESENCE_OF_CC 0.0016169487930743943
LT_TV_DAILY_VIEWING_V2 0.0016896794606214248
CHANNELSD_BANNER_SCALE 0.0017116759218621972
SPENDEX_PLUS_V2 0.0017182865722678903
ZIPCAR_USER 0.0017210916191145464
HW_SMOKING 0.001773874643196334
SPENDEX_PERSONAL_V2 0.0020357035490465064
HOME_PURCHASE_PRICE 0.0020548307389588938
OS_FIN_IMPCONTROL 0.0021542929815902777
SOCIALSD_DEAL_SITE 0.002169387988675451
INMARKET_ONLINEEDU_V2 0.0021932942899590357
SD_GENDER 0.00231433015411826
LT_PET_OWNER_V2 0.0025258817753156084
INMARKET_ONLINEDATE 0.0026246065578568283
SD_HOME_AGE 0.0027893126622680372
ZIP5 0.003051255457456939
LT_GOLF_FAN_V2 0.0031210493357922055
SD_LOR_V2 0.003195308812583672
LT_GAMING_ESPORTS 0.0032467564212921404
OS_COOKING 0.0032920825623483745
ONLINE_PAYMENT 0.0033056085615048546
LIKELIHOODINTEREST_ONLINEPAYMENT 0.0036164281372644195
CHANNELSD_INTERTV_SCALE 0.0036398804955405034
OS_FIN_PLANNING 0.0038945712848934802
TV_FAVORITES_LIVE_SPORTS 0.003938470086563794
LT_TRAVEL_DOMESTIC_V2 0.004582551758224077
SMARTPHONE_NONE_SCALE 0.004738764303629114
UBER_LYFT_USER 0.004805468101297367
INMARKET_TERM_LIFE 0.00523974352703502
TV_STREAMING_SERV_MANY 0.005634998611198484
SD_BUSINESS_OWNER_V2 0.006032648562299065
TV_VIEWER_EMPATHIZER 0.006578145812361028
AUTO_AGE 0.007575879905198194
JOBSSD_CORP_LEADER 0.007767330782626542
SPENDEX_EDUCATION_V2 0.00784816610883383
INCOME_GROUP 0.008725178219848057
REGB_CC_AIRLINE_IM 0.008784010081336965
HW_JOB_SATIS 0.010921477630977382
SMARTPHONE_ANDROID_SCALE 0.011425586949583727
SPENDEX_TRAVEL_V2 0.011426591220179694
OS_MATERIALISM 0.014609856094774965
TRAVELPROP 0.01711507407805317
SOCIALSD_TUMBLR 0.019763670047014997
TV_FAVORITES_NEWS 0.024344053038245127
OS_LAGGARD 0.038745248104943335
CHANGE_IN_HOME_VALUE_12MO 0.07766876927783799
HW_SLEEP_V3 0.08656163191773675
HW_STRESS_V2 0.49052803830950825

In [ ]:
# GAP

In [28]:
## CLUSTER 4

# Preparing file for cluster_4 prediction

# First make predictions using the decision tree for Cluster 1
predictions1 = dt.predict(features_no02) 
df_sahara2_no02['predictions1'] = predictions1
df_sahara2_no02

,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,SMARTPHONE_NONE_SCALE,...,SOCAILMEDIA_INFLUENER,EXERCISE_INTEREST_RATING,EXERCISE,LIKELIHOODINTEREST_ONLINEPAYMENT,cluster_2,cluster_1,cluster_4,cluster_0,cluster_3,predictions1
1,72212,1,4,0,5,2,1,5,6,2,...,7,7,1,5.0,0,1,0,0,0,1
3,60085,6,1,0,2,2,6,2,1,7,...,4,7,1,2.0,0,0,1,0,0,0
5,60629,4,1,0,6,7,3,6,6,2,...,6,7,1,5.5,0,1,0,0,0,1
8,60020,7,5,0,6,4,4,3,3,6,...,5,6,0,2.5,0,1,0,0,0,1
9,95409,6,2,0,4,1,6,4,5,6,...,7,6,1,4.0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8166062,95118,6,4,0,7,7,2,4,7,3,...,7,7,1,5.0,0,0,0,0,1,0
8166064,60448,6,2,0,1,1,4,1,7,2,...,7,7,1,1.0,0,0,1,0,0,0
8166065,94920,7,6,1,3,3,2,1,7,3,...,7,7,1,4.5,0,0,0,0,1,0
8166066,60101,3,4,0,5,7,3,5,6,2,...,6,6,1,6.0,0,1,0,0,0,1
8166068,60051,4,4,0,3,1,7,4,2,6,...,4,5,0,2.0,0,0,1,0,0,0

In [29]:
#drop columns 
df_sahara2_no021 = df_sahara2_no02[df_sahara2_no02["predictions1"] < 0.5].drop("predictions1", axis=1)

In [30]:
#Preview
df_sahara2_no021

,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,SMARTPHONE_NONE_SCALE,...,ONLINE_PAYMENT,SOCAILMEDIA_INFLUENER,EXERCISE_INTEREST_RATING,EXERCISE,LIKELIHOODINTEREST_ONLINEPAYMENT,cluster_2,cluster_1,cluster_4,cluster_0,cluster_3
3,60085,6,1,0,2,2,6,2,1,7,...,2.5,4,7,1,2.0,0,0,1,0,0
9,95409,6,2,0,4,1,6,4,5,6,...,2.0,7,6,1,4.0,0,0,1,0,0
10,94928,7,2,0,4,3,6,2,6,3,...,2.0,6,7,1,5.5,0,0,1,0,0
11,60025,7,3,0,3,1,3,1,7,4,...,2.5,7,5,1,3.5,0,0,1,0,0
15,94123,7,2,0,3,3,3,2,7,3,...,4.0,7,6,1,5.0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8166061,95123,7,2,0,4,5,4,4,7,2,...,4.0,6,6,1,5.5,0,0,0,0,1
8166062,95118,6,4,0,7,7,2,4,7,3,...,4.5,7,7,1,5.0,0,0,0,0,1
8166064,60448,6,2,0,1,1,4,1,7,2,...,2.0,7,7,1,1.0,0,0,1,0,0
8166065,94920,7,6,1,3,3,2,1,7,3,...,4.5,7,7,1,4.5,0,0,0,0,1
8166068,60051,4,4,0,3,1,7,4,2,6,...,2.0,4,5,0,2.0,0,0,1,0,0

In [31]:
# Model building for cluster_4

# Create a dataframe with just the features without clusters 
features_no021 = df_sahara2_no021.drop(['cluster_0', 'cluster_1', 'cluster_2', 'cluster_3', 'cluster_4'], axis = 1)
features_no021

,ZIP5,AUTO_AGE,AUTO_AVG_MILEAGE,AUTOMOTIVE_BUFF_V2,CHANNELSD_BANNER_SCALE,CHANNELSD_INTERTV_SCALE,LT_TV_DAILY_VIEWING_V2,SMARTPHONE_ANDROID_SCALE,SMARTPHONE_IPHONE_SCALE,SMARTPHONE_NONE_SCALE,...,CHILDREN_AGED_0_10,CHILDREN_AGED_11_17,GAMING_ESPORTS,LT_GAMING_ESPORTS,LT_HUNTING,ONLINE_PAYMENT,SOCAILMEDIA_INFLUENER,EXERCISE_INTEREST_RATING,EXERCISE,LIKELIHOODINTEREST_ONLINEPAYMENT
3,60085,6,1,0,2,2,6,2,1,7,...,0,0,0.0,1.0,2.0,2.5,4,7,1,2.0
9,95409,6,2,0,4,1,6,4,5,6,...,0,0,0.0,1.5,2.0,2.0,7,6,1,4.0
10,94928,7,2,0,4,3,6,2,6,3,...,1,1,0.0,2.0,1.0,2.0,6,7,1,5.5
11,60025,7,3,0,3,1,3,1,7,4,...,1,1,0.0,2.5,1.5,2.5,7,5,1,3.5
15,94123,7,2,0,3,3,3,2,7,3,...,0,0,0.0,3.0,2.0,4.0,7,6,1,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8166061,95123,7,2,0,4,5,4,4,7,2,...,1,1,0.0,3.5,1.0,4.0,6,6,1,5.5
8166062,95118,6,4,0,7,7,2,4,7,3,...,1,1,0.0,4.0,1.0,4.5,7,7,1,5.0
8166064,60448,6,2,0,1,1,4,1,7,2,...,0,0,0.0,2.0,1.5,2.0,7,7,1,1.0
8166065,94920,7,6,1,3,3,2,1,7,3,...,0,0,0.0,3.0,4.0,4.5,7,7,1,4.5
8166068,60051,4,4,0,3,1,7,4,2,6,...,1,1,0.0,1.0,3.0,2.0,4,5,0,2.0

In [32]:
# Let's start with Logistic again
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no021
y = df_sahara2_no021['cluster_4']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a logistic regression model
logreg = LogisticRegression(random_state=42)

# Train the model on the training data
logreg.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = logreg.predict(X_test)

# Evaluate the performance of the model
accuracy = logreg.score(X_test, y_test)
print("Accuracy:", accuracy)

/opt/conda/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,

Accuracy: 0.8755314413886952

In [33]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[236370  39680]
 [ 38341 312442]]

In [35]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X = features_no021
y = df_sahara2_no021['cluster_4']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a decision tree classifier
dt = DecisionTreeClassifier(random_state=42)

# Train the classifier on the training data
dt.fit(X_train, y_train)

# Predict the cluster for the testing data
y_pred = dt.predict(X_test)

# Evaluate the performance of the model
accuracy = dt.score(X_test, y_test)
print("Accuracy:", accuracy)

Accuracy: 0.9781361223802831

In [36]:
from pandas._libs.tslibs import dtypes
import numpy as np
# Get the feature importances 
importances = dt.feature_importances_ 

# Get the indices that would sort the importances in ascending order
sorted_indices = np.argsort(importances)
# Print the feature importances in ascending order
for feature, importance in zip(X.columns[sorted_indices], importances[sorted_indices]):
   print(feature, importance)

SPEC_SPORT_AUTO_MC_V2 0.0
TEAM_SPORTS_V2 0.0
PREMOVER_NEW_OWNER_V2 0.0
GAMING_ESPORTS 0.0
AUTOMOTIVE_BUFF_V2 3.627968128984915e-05
JOB_SEEKER_ACTIVE 4.234422865649425e-05
CC_USER 5.855903431590218e-05
PARENTING_CATEGORY 6.474821455582352e-05
JEWELRY_PURCHASER 6.654046570712805e-05
JOB_SEEKER 7.644640767833722e-05
PRESENCE_OF_CC 7.689351787966841e-05
CHILDREN_AGED_0_10 8.37152027143077e-05
ONLINE_PURCHASER 8.589516928907782e-05
CC_NEW_ISSUE 9.048778210235775e-05
YOUNG_ADULT_IN_HH 9.103629099409709e-05
MAGAZINE_READER 0.00010191948488757941
TV_CABLE_V2 0.00010268862133700384
CHILDREN_AGED_11_17 0.00011026188192752184
AGE_GROUP 0.00011844524508697328
VALUE_HUNTER 0.00012149109049850435
EXERCISE 0.00014959209052867967
APPAREL_WOMEN_PLUS_V2 0.00016136112008615652
HEALTH_BEAUTY 0.00016879101371078677
PRESENCE_OF_CHILDREN 0.00016890090631952582
BEAUTY_COSMETICS 0.00018107850952009432
HOME_DECORATING_FAN_V2 0.00020171425029425993
LT_SPEC_SPORT_AUTO_MC_V2 0.00020444283242979582
HW_JUNK_DIET 0.00020546689679169252
SD_HOMEOWNER_PROB_V2 0.0002139311900412018
TV_FAVORITES_LIVE_SPORTS 0.0002381890183680423
SD_GENDER 0.00024620288145462646
CHANGE_IN_INCOME_12MO 0.0002730173622704114
SD_CHILDREN_IN_HH 0.0002745297183452109
OS_FIN_PLANNING 0.0002790545475410979
SD_ADULTS_IN_HH 0.0002832651260307754
HW_STRESS_V2 0.0002863725831169234
REGB_CC_AIRLINE_IM 0.0002985537147532177
JOBSSD_RETIRED 0.00032758262886435814
JOBSSD_MIDDLE_MGMT 0.0003324267804073493
TV_FAVORITES_HOME_IMP 0.0003374217814724646
SD_EDUCATION_V2 0.0003419314667620952
JOBSSD_STUDENT 0.0003478100482031325
LT_FISHING_FAN_V2 0.00035211589879270775
HS_TRAVEL_BUSINESS 0.0003526962591937889
INMARKET_TERM_LIFE 0.00035485101170077104
OS_VALUE_SEEKER 0.0003611729424369232
LT_HOME_FURNISHINGS_DECO_V2 0.00036639923795170863
EXERCISE_INTEREST_RATING 0.0003679765326242845
JOBSSD_BLUE_COLLAR 0.0003741396097728913
AUTO_AGE 0.0003867782154834703
HW_SMOKING 0.00038788057952964113
SD_PEOPLE_IN_HH 0.00040145927586194235
TV_STREAMING_SERV_MANY 0.000404882232774529
JOBSSD_SALES 0.0004106159227569864
ETHNICSD_V2 0.0004113602882540828
PREMOVER_V2 0.0004208706379835561
CHANNELSD_BANNER_SCALE 0.00042339048301039546
LT_HOME_GARDEN_V2 0.0004427312399307946
JOBSSD_HOMEMAKER 0.00044560840828305917
LT_CAMPING_FAN_V2 0.0004726091944390878
OS_FIN_IMPCONTROL 0.00047748982530132164
HW_JOB_SATIS 0.00048182695600526744
JOBSSD_CORP_LEADER 0.000489544009887953
HW_SLEEP_V3 0.0004926683629316615
SMARTPHONE_ANDROID_SCALE 0.0005039106262911472
TV_FAVORITES_NEWS 0.0005047047413856115
OS_COOKING 0.000509973649043657
REGB_FINTECH_MWALLET 0.0005146198553727649
LT_HUNTING 0.0005297687550821792
LT_HOME_IMPROVEMENT_V2 0.0005481531930179799
HW_DIET 0.0005832402984668437
OS_RISKTAKING_FIN 0.0005857044514321069
TV_VIEWER_EMPATHIZER 0.0006002779111712081
LT_PET_OWNER_V2 0.0006027271002576846
CHANNELSD_INTERTV_SCALE 0.000610803021182083
LT_TEAM_SPORTS_V2 0.0006268708430329703
TRAVELPROP 0.0006523460897762693
LT_GOLF_FAN_V2 0.0006712401549639446
AUTO_AVG_MILEAGE 0.0007158762700292772
REGB_FINTECH_DIGITAL 0.0008564638067955949
SD_EMPLOYMENT 0.000880141924921757
OS_MATERIALISM 0.0009848539308810337
SOCAILMEDIA_INFLUENER 0.0010373309552180088
LT_SENIOR_ADULT_IN_HH_V2 0.0010376100417688828
OS_INNOVATOR 0.0010621757021082485
SPENDEX_TRAVEL_V2 0.001138383511835656
HOME_PURCHASE_PRICE 0.001152581506021725
SD_HOME_AGE 0.0011986428772061762
ZIP5 0.0012067689772477116
SD_LOR_V2 0.00122153450771953
LT_DEAL_SITE 0.0013328153777303789
SOCIALSD_DEAL_SITE 0.0014050819596307155
INMARKET_ONLINEDATE 0.001423798456541973
SPENDEX_PERSONAL_V2 0.0014533648988218583
SPENDEX_APPAREL_V2 0.0014814289104457536
ZIPCAR_USER 0.0015149440956945515
LT_EXERCISE 0.0015262042406359428
OS_FOODIE 0.0015958491437254767
LT_COUPONER 0.0017655294909502814
SMARTPHONE_NONE_SCALE 0.001925589327195142
UBER_LYFT_USER 0.0022295360286488587
CHANGE_IN_HOME_VALUE_12MO 0.002308112114297425
LIKELIHOODINTEREST_ONLINEPAYMENT 0.0025581452773264252
LT_TV_DAILY_VIEWING_V2 0.0030250643635197846
SMARTPHONE_IPHONE_SCALE 0.003051132885507346
INCOME_GROUP 0.00405143531864356
LT_TRAVEL_DOMESTIC_V2 0.005566560272179537
SOCIALSD_TRIP_ADVISOR 0.006025359381735069
SPENDEX_PLUS_V2 0.008255268960828935
INMARKET_ONLINEEDU_V2 0.008865490200210114
SOCIALSD_TUMBLR 0.009846723193576499
OS_LAGGARD 0.015783483692870047
ONLINE_PAYMENT 0.018050337515492332
SD_BUSINESS_OWNER_V2 0.027312948380125948
SPENDEX_EDUCATION_V2 0.044379042199492465
LT_GAMING_ESPORTS 0.06837026827413427
OUTDOOR_GROUPING_V2 0.71843132542667

In [37]:
#confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[269352   6698]
 [  7007 343776]]

In [40]:
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import train_test_split

# Load the data into a pandas dataframe

# Split the data into training and testing sets
X = features_no021
y = df_sahara2_no021['cluster_4']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Set up the XGBoost model
params = {'objective': 'binary:logistic', 'eval_metric': 'auc'}
num_rounds = 10
early_stopping_rounds = 50
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)

# Train the model
model = xgb.train(params, dtrain, num_rounds, evals=[(dtest, 'test')], early_stopping_rounds=early_stopping_rounds)

# Make predictions on the test set
y_pred = model.predict(dtest)

# Calculate the accuracy score
threshold = 0.5
y_pred_binary = [1 if p > threshold else 0 for p in y_pred]
accuracy = sum(y_pred_binary == y_test) / len(y_test)
print('Accuracy: %.2f%%' % (accuracy * 100.0))

[0]	test-auc:0.99360
[1]	test-auc:0.99584
[2]	test-auc:0.99646
[3]	test-auc:0.99735
[4]	test-auc:0.99784
[5]	test-auc:0.99810
[6]	test-auc:0.99825
[7]	test-auc:0.99844
[8]	test-auc:0.99854
[9]	test-auc:0.99871
Accuracy: 98.49%

In [41]:
#confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred_binary)
print("Confusion matrix: ")
print(cm)

Confusion matrix:
[[405402   8720]
 [  5475 520653]]